### ISSUE TITLE
interface media copper must be set before speed in /etc/goes/start

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#10]
In /etc/goes/start, interface media copper config must come before interface speed config if running copper (i.e. cable).  Otherwise autoneg or fixed speed will not tune the adaptive DFE and therefore result in a sub optimal received eye that could lead to crcs or link flap.

In general, media copper setting must be done before speed setting.  For example manually via redis.

If not done in correct order, then issue speed setting in redis again to trigger the adaptive DFE to start again.

**Comment by dlobete** [comment]
Please retest with this commit:

commit 6fa4a9f8172459f10a52b0a75f455a7a25b1da48
Author: Don Lobete <dlobete@platinasystems.com>
Date:   Fri Feb 3 10:35:20 2017 -0800

    Do a speed change with speed on record when setting media for a port.
    
    Signed-off-by: Don Lobete <dlobete@platinasystems.com>

**Comment by fszyang** [comment]
Confirmed fixed.  Order no longer matter now.  Closing this issue out.
