### ISSUE TITLE
Redis not gracefully handling hset on sub-ports that are not valid interfaces

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#103]
For example if eth-1-1 is a 100g port (4 lane), eth-1-2/eth-1-3/eth-1-4 should not be available as valid interfaces.

Bug:
goes hset platina vnet.eth-1-3.media copper
will actually create an eth-1-3 interface in redis when it shouldn't

goes hset platina vnet.eth-1-3.fec (or speed)
will crash rather than reject.  If a fictitious eth-1-3 was created by hset media, then hset fec/speed will actually succeed when it shouldn't.

**Comment by jskhedkarl** [comment]
@fszyang please review code changes under pull request https://github.com/platinasystems/fe1/pull/3.

**Comment by fszyang** [comment]
Fixed with commit 81fa7ef3e3f0637dc5d8281f9bd235e4df4e3c6a
