### ISSUE TITLE
In 10g port provisioning media type for few interfaces are setting to fiber rather than copper

### ISSUE THREAD

**Issue by sans2864** [platinasystems/go#121]
Tested with the following goes version
Build version:

version: dce65f7bbc20d4774ceff97e77f9633c0a26b9e9
version: f9c448619d8909ccc356e16ee372491a3f441c54
version: 60f39141fbbf78ddb2260dba74c68f2789374f18

Observed that following port provisioning test cases are failing while executing the playbooks for the same. 

1. port_provision_10g_cr_fec_cl74_autoeng_on_lanes_1_count_4
2. port_provision_10g_cr_fec_none_autoeng_on_lanes_1_count_4

We found that somehow on eth-1-2 to eth-1-4, the media type is setting to fiber rather than copper
root@invader29:/home/sandeep# goes hget platina media
vnet.eth-1-1.media: copper
vnet.eth-1-2.media: fiber
vnet.eth-1-3.media: fiber
vnet.eth-1-4.media: fiber

root@invader31:/etc/goes# goes hget platina media
vnet.eth-1-1.media: copper
vnet.eth-1-2.media: fiber
vnet.eth-1-3.media: fiber
vnet.eth-1-4.media: fiber

However the link status between the above mentioned links are set to True & we can pass iperf traffic between these interfaces

root@invader29:/home/sandeep# goes hget platina link
vnet.eth-1-1.link: true
vnet.eth-1-2.link: true
vnet.eth-1-3.link: true
vnet.eth-1-4.link: true

root@invader31:/etc/goes# goes hget platina link
vnet.eth-1-1.link: true
vnet.eth-1-2.link: true
vnet.eth-1-3.link: true
vnet.eth-1-4.link: true

Attached are the manual steps for test case execution
[10G CR fec=cl74-Autoneg ON Lanes1 Counts4.docx](https://github.com/platinasystems/go/files/1915398/10G.CR.fec.cl74-Autoneg.ON.Lanes1.Counts4.docx)

[10G CR fec=none-Autoeng=ON Lanes1 Counts4.docx](https://github.com/platinasystems/go/files/1915401/10G.CR.fec.none-Autoeng.ON.Lanes1.Counts4.docx)

**Comment by arthurxiong3** [comment]
Could you highlight and briefly describe what's wrong in the attachments? I can't find 'fiber' from those two docx files.

**Comment by sans2864** [comment]
The attachments are the test cases which explains step by step manual execution of the above mentioned 10g scenarios. It does not includes the issue which we are observing currently.The actual media output containing the issue is mentioned above

As you can see from the test steps the media is never set to fiber (hence you can't find fiber in docx files).However from the output above the media type is getting set to fiber.

The same test case & corresponding playbooks were successfully passing on the earlier release.

The corresponding playbooks for executing these test cases can be found on 172.17.2.28 under

/home/sandeep/go/ansible/regtest/playbooks/port_provision/10g_cr_fec_cl74_autoeng_on_lanes_1_count_4.yml

/home/sandeep/go/ansible/regtest/playbooks/port_provision/10g_cr_fec_none_autoeng_on_lanes_1_count_4.yml

**Comment by arthurxiong3** [comment]
> The same test case & corresponding playbooks were successfully passing on the earlier release.
Which release/build is the last one passed this test case?

**Comment by arthurxiong3** [comment]
> The attachments are the test cases which explains step by step manual execution of the above 
> mentioned 10g scenarios.

Which release/build was used for generating the results for the steps? Have these manual steps been manually executed on the build running into the issue?

**Comment by sans2864** [comment]
I am not sure about the build we used to write the test cases but these test case documents have been create 2 to 3 months ago.

The details of the previous build where test case was passing( where media type was set correctly to copper) is mentioned below

 version: 30f396d35e419a5cc0006e9305a91ca31ce8cdd5
 version: 716f29ca72f20ac3288bbd2857eb55cfcadb63eb
 version: 60f39141fbbf78ddb2260dba74c68f2789374f18

Also I noticed on common problem on the current build and previous build for above test cases that some how eth-15-3 link between the invaders 29 & 31 fails to pass any traffic, in fact ping between these interfaces also does not work although the link status is set to True on both the invaders. This parameter also causes the playbook to fail.

vnet.eth-15-3.media: copper
vnet.eth-15-3.fec: cl74
vnet.eth-15-3.link: true

vnet.eth-15-3.media: copper
vnet.eth-15-3.fec: cl74
vnet.eth-15-3.link: true

**Comment by sans2864** [comment]
We can reproduce the issue by manual execution as well.

**Comment by arthurxiong3** [comment]
> Also I noticed on common problem on the current build and previous build for above test cases that 
> some how eth-15-3 link between the invaders 29 & 31 fails to pass any traffic, in fact ping between 
> these interfaces also does not work although the link status is set to True on both the invaders. This 
> parameter also causes the playbook to fail.However this issue only occurs on setup-1 & not in setup-2.

Create a new issue about it if there's no existing one covers it.

**Comment by arthurxiong3** [comment]
I reproduce it -
`arthur@invader29:~$ grep -A4 eth-1- /etc/goes/portprovision
- name: eth-1-1
  speed: 10g
  lanes: 1
  count: 4
arthur@invader29:~$ grep eth-1- /etc/goes/start
hset -q platina vnet.eth-1-1.media copper
hset -q platina vnet.eth-1-1.speed auto
hset -q platina vnet.eth-1-1.fec none
hset -q platina vnet.eth-1-2.media copper
hset -q platina vnet.eth-1-2.speed auto
hset -q platina vnet.eth-1-2.fec none
hset -q platina vnet.eth-1-3.media copper
hset -q platina vnet.eth-1-3.speed auto
hset -q platina vnet.eth-1-3.fec none
hset -q platina vnet.eth-1-4.media copper
hset -q platina vnet.eth-1-4.speed auto
hset -q platina vnet.eth-1-4.fec none
arthur@invader29:~$ sudo goes hget platina media | grep eth-1-
vnet.eth-1-1.media: copper
vnet.eth-1-2.media: copper
vnet.eth-1-3.media: fiber
vnet.eth-1-4.media: fiber
arthur@invader29:~$ sudo goes -version
github.com/platinasystems/go: v0.41-20-gdce65f7
github.com/platinasystems/fe1: v0.4-17-gf9c4486
github.com/platinasystems/firmware-fe1a: v0.2
`
vs.

`
arthur@invader31:~$ sudo goes -version
github.com/platinasystems/go: v0.4
github.com/platinasystems/fe1: v0.4
github.com/platinasystems/firmware-fe1a: v0.2
arthur@invader31:~$ grep eth-1- /etc/goes/start
hset -q platina vnet.eth-1-1.media copper
hset -q platina vnet.eth-1-1.speed auto
hset -q platina vnet.eth-1-1.fec none
hset -q platina vnet.eth-1-2.media copper
hset -q platina vnet.eth-1-2.speed auto
hset -q platina vnet.eth-1-2.fec none
hset -q platina vnet.eth-1-3.media copper
hset -q platina vnet.eth-1-3.speed auto
hset -q platina vnet.eth-1-3.fec none
hset -q platina vnet.eth-1-4.media copper
hset -q platina vnet.eth-1-4.speed auto
hset -q platina vnet.eth-1-4.fec none
arthur@invader31:~$ grep -A4 eth-1- /etc/goes/portprovision
- name: eth-1-1
  speed: 10g
  lanes: 1
  count: 4
arthur@invader31:~$ sudo goes hget platina media | grep eth-1-
vnet.eth-1-1.media: copper
vnet.eth-1-2.media: copper
vnet.eth-1-3.media: copper
vnet.eth-1-4.media: copper
`

**Comment by arthurxiong3** [comment]
even eth-1-2 is set with static IP as eth-1-1, eth-1-2 media still is 'fiber'
[issue121_ax1.txt](https://github.com/platinasystems/go/files/1930180/issue121_ax1.txt)

**Comment by fszyang** [comment]
I’m looking into this on invader29 right now

**Comment by fszyang** [comment]
Not a bug.  In /etc/goes/start please put set speed before set media.  

In the "bad" /etc/goes/start that was on invader29, on goes restart, you can see error messages
```
hset: ERROR invalid speed: PLL does not match mainPort(first subPort of PortBlock)
```
This is happening because set media came before set speed on a subport interface.  When error happens, obviously the /etc/goes/start did not source properly and so some media were not set.

The reason it has to be this order (for subports) is because
1. Set media triggers a speed/PLL update because going from fiber to copper, for example, requires starting link training.
2. Subports must match the PLL setting of the main port.  Ideally subports should be the same speed as the main port.  Only a main port can change the PLL speed.
3.  When eth-1-1, for example, changed from 10g to autoneg, PLL is changed because eth-1-1 is a main port.
4.  When eth-1-2 tries to set media to copper, it tries to set speed to 10g (what it was previously configured) to trigger link training, and GOES rejects because PLL is already taken by main port to autoneg.
5.  Setting eth-1-2 speed to autoneg is OK because it matches eth-1-1.
6.  Now if you set eth-1-2 media to copper again, everything is OK as it applies the autoneg setting again which matches main port.

**Comment by sans2864** [comment]
Thanks for detailed explanation Frank.

I have made suggested changes on the start file and now I can see the correct media type being set on the interfaces.

Also ping fail issue between eth-15-3 of invader-29 & invader-31 does not occurs anymore.

Closing the issue.
