### ISSUE TITLE
Unable to configure autoneg=ON option while port provisioning an interface on master branch

### ISSUE THREAD

**Issue by sandeep-dutta** [platinasystems/go#123]
Observed autoneg=ON option is not working while port provisioning an interface on master branch

Goes version:
root@invader45:/home/sandeep/portprovision_testcases# goes version
github.com/platinasystems/go: v0.41-183-g9b6beab9
github.com/platinasystems/fe1: v0.2-515-gc1fa302
github.com/platinasystems/firmware-fe1a: v0.2

Kernel Version:
root@invader45:/home/sandeep/portprovision_testcases# dpkg --list |grep kernel
ii  kmod                           18-3                             amd64        tools for managing Linux kernel modules
**ii  linux-image-4.13.0-platina-mk1 4.13-101-g318aed87b97c           amd64        Linux kernel, version 4.13.0-platina-mk1**
ii  rsyslog                        8.4.2-1+deb8u2                   amd64        reliable system and kernel logging daemon

Steps to reproduce

- Used the following cmds to create port-provision interfaces between eth-1-1 interface of invader-45 & invader-43 for 10G port provisioning

- Invader-45
goes stop
rmmod platina-mk1
modprobe platina-mk1
ip link add eth-1-1 type platina-mk1  
ip link set eth-1-1 up
ethtool -s eth-1-1 speed 10000 autoneg on
ifconfig eth-1-1 10.1.1.29/24
goes start

- Invader-43
goes stop
rmmod platina-mk1
modprobe platina-mk1
ip link add eth-1-1 type platina-mk1  
ip link set eth-1-1 up
ethtool -s eth-1-1 speed 10000 autoneg on
ifconfig eth-1-1 10.1.1.31/24
goes start

- Observed that while firing the cmd **ethtool -s eth-1-1 speed 10000 autoneg on**, got the following errors

root@invader45:/home/sandeep/portprovision_testcases# ethtool -s eth-1-1 speed 10000 autoneg on
Cannot advertise speed 10000
Driver supports one or more unknown flags

Similar issue is happening while setting link speed to autoneg=ON for 10G, 100G, 40G port provisioning cases.

**Comment by sandeep-dutta** [comment]
Issue is reproducible with the following goes version
root@invader45:/home/sandeep# goes version
github.com/platinasystems/go: v0.41-244-g49d9e6da
github.com/platinasystems/fe1: v0.2-520-g85494c1
github.com/platinasystems/firmware-fe1a: v0.2

**Comment by fszyang** [comment]
To turn autoneg on, do autongen on without the speed setting
example:
ethtool -s eth-1-1 autoneg on

**Comment by sandeep-dutta** [comment]
I tried the same but still getting driver support error for the interface
root@invader29:/home/sandeep# ethtool -s eth-1-2 autoneg on
Driver supports one or more unknown flags

Below are goes & kernel version
root@invader29:/home/sandeep# goes version
github.com/platinasystems/go: v0.41-332-g3d923a20
github.com/platinasystems/fe1: v0.2-529-ga5f1fd4

root@invader29:/home/sandeep# dpkg --list | grep kernel
ii  linux-image-4.13.0-platina-mk1 4.13-134-g39fbcf8c984f           amd64        Linux kernel, version 4.13.0-platina-mk1
