### ISSUE TITLE
Custom interface file not taking updated changes after restarting goes & networking service

### ISSUE THREAD

**Issue by sandeep-dutta** [platinasystems/go#125]
Goes version:
root@invader45:/home/sandeep# goes version
github.com/platinasystems/go: v0.41-214-g7bc026cd
github.com/platinasystems/fe1: v0.2-520-g85494c1
github.com/platinasystems/firmware-fe1a: v0.2

Kernel Version:
root@invader45:/home/sandeep# dpkg --list |grep kernel
ii  kmod                           18-3                             amd64        tools for managing Linux kernel modules
ii  linux-image-4.13.0-platina-mk1 4.13-104-g3780791c9a4b           amd64        Linux kernel, version 4.13.0-platina-mk1
ii  rsyslog                        8.4.2-1+deb8u2                   amd64        reliable system and kernel logging daemon

Observations:

Observed that when we copy custom interfaces file to /etc/network/interfaces and restart networking service & goes service, we don't see the updated changes taking effect as configured on interfaces_custom file. Once we reboot the invader we can see the updated changes.

Please find the attached custom and default network interfaces files.You can get the files on invader-45 also under /home/sandeep. Note that in interfaces_custom file we have disabled eth-31-1 & eth-32-1 configurations and on interfaces_default file all the interfaces from eth-1-1 to eth-32-1 are configured.

[interfaces_custom.txt](https://github.com/platinasystems/go/files/2139790/interfaces_custom.txt)
[interfaces_default.txt](https://github.com/platinasystems/go/files/2139791/interfaces_default.txt)

**Comment by sandeep-dutta** [comment]
Issue persists with the following goes version

root@invader45:/home/sandeep# goes version
github.com/platinasystems/go: v0.41-244-g49d9e6da
github.com/platinasystems/fe1: v0.2-520-g85494c1
github.com/platinasystems/firmware-fe1a: v0.2

**Comment by fszyang** [comment]
Instead of restarting networking service, do this:

Assuming the front panel interface have configs like this:
```
allow-vnet eth-1-1
auto eth-1-1
iface eth-1-1 inet static
  address 10.10.1.34
  netmask 255.255.255.0
  pre-up ip link add $IFACE type platina-mk1
  pre-up ip link set $IFACE up
  pre-up ethtool -s $IFACE speed 100000 autoneg off
  post-down ip link set $IFACE down
```

copy over custom file to /etc/network/interface
run
```
goes stop
rmmod platina-mk1
modprobe platina-mk1
ifdown -a --allow vnet
ifup -a
goes start
```

**Comment by sandeep-dutta** [comment]
I tried the above & now I don't see RTNETLINK error message for the interfaces.

**Comment by RohanK-Calsoft** [comment]
No RTNETLINK error message for the interfaces are observed now and moreover, We are now using 'ifup -a --allow vnet' and 'ifdown -a --allow vnet' commands instead of networking restart in all the test-steps. This bug can be closed now.
