### ISSUE TITLE
Unable to set media on port provisioned interface under master branch

### ISSUE THREAD

**Issue by sandeep-dutta** [platinasystems/go#126]
Issue observed on the following goes version
root@invader45:/home/sandeep/portprovision_testcases# goes version
github.com/platinasystems/go: v0.41-244-g49d9e6da
github.com/platinasystems/fe1: v0.2-520-g85494c1
github.com/platinasystems/firmware-fe1a: v0.2

Observations:
Unable to update media type of port provisioned interfaces.
Steps to reproduce.
- Set port provision for an interface to 25g
- Try to set media of the provisioned interface using the below cmd. Goes throws the following errors and fails to set the media type as requested.

root@invader45:/home/sandeep/portprovision_testcases# goes hset platina-mk1 vnet.eth-1-2.media copper
hset: ERROR invalid speed: PLL does not match mainPort(first subPort of PortBlock)

**Comment by fszyang** [comment]
Fixed in commit aa6b634a0548a66703fd379e26677c12263f752a

**Comment by sandeep-dutta** [comment]
Bug verified & fixed with aa6b634a0548a66703fd379e26677c12263f752a

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.1.1

BuildID[sha1]=5046b7c2cdea8604d331dd7e5dd2fb9c85fa21ff

Error not reproducing anymore can be closed now. Redis not throwing any error message. (Checked for fiber as well, working fine)
