### ISSUE TITLE
Interface speed sets to autoneg after configuring them with 40G speed under port provision

### ISSUE THREAD

**Issue by sandeep-dutta** [platinasystems/go#132]
While configuring port provision with speed set to 40G lane-2 count-2 with autoneg off, noticed that out  of 2 interfaces, one of the interfaces speed sets to autoneg. Also tried manually setting the speed to 40g but goes does not accepts it.

root@invader45:/home/sandeep/pp# goes hget platina-mk1 speed |grep eth-1-
vnet.eth-1-1.speed: 40g
vnet.eth-1-2.speed: autoneg

root@invader45:/home/sandeep/pp# goes hset platina-mk1 vnet.eth-1-2.speed 40g
hset: ERROR Interface eth-1-2 is not provisioned

To execute the above case we created custom interface files and copied it to /etc/network/interfaces than we configure fec & media parameters. Below are the configuration for the interfaces provisioned for 40g

allow-vnet eth-1-1
auto eth-1-1
iface eth-1-1 inet static
    address 10.1.1.29
    netmask 255.255.255.0
pre-up ip link add $IFACE type xeth
pre-up ip link set $IFACE up
pre-up ethtool -s $IFACE speed 40000 autoneg off
post-down ip link set $IFACE down
post-down ip link del $IFACE type xeth
allow-vnet eth-1-1

allow-vnet eth-1-2
auto eth-1-2
iface eth-1-2 inet static
    address 10.1.2.29
    netmask 255.255.255.0
pre-up ip link add $IFACE type xeth
pre-up ip link set $IFACE up
pre-up ethtool -s $IFACE speed 40000 autoneg off
post-down ip link set $IFACE down
post-down ip link del $IFACE type xeth
allow-vnet eth-1-2

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.1.1

BuildID[sha1]=5046b7c2cdea8604d331dd7e5dd2fb9c85fa21ff

This error is not reproducing anymore (and as for 40g Lane2-Count2 is not valid anyway). This Bug can be closed.

**Comment by sandeep-dutta** [comment]
Closing the bug since 40g lane2 count2 combination is not supported.
