### ISSUE TITLE
vnet devices are republishing old counts

### ISSUE THREAD

**Issue by tgrennan** [platinasystems/go#14]
Note eth-31-0.* are repating with same counts...

$ goes subscribe platina
eth0.rx_packets: 162505931
eth0.tx_packets: 141682625
eth0.rx_bytes: 17609416052
eth0.tx_bytes: 10567673774
eth-31-0.tx_pipe_multicast_queue_cos0_packets: 7
eth-31-0.tx_pipe_multicast_queue_cos0_bytes: 738
eth-31-0.port_tx_packets: 7
eth-31-0.port_tx_bytes: 766
eth-31-0.port_tx_65_to_127_byte_packets: 5
eth-31-0.port_tx_128_to_255_byte_packets: 2
eth-31-0.port_tx_good_packets: 7
eth-31-0.port_tx_multicast_packets: 7
eth-31-0.tx_packets: 7
eth-31-0.tx_bytes: 738
eth-31-0-unix.rx_packets: 7
eth-31-0-unix.rx_bytes: 738
eth0.rx_packets: 162506230
eth0.tx_packets: 141682899
eth0.rx_bytes: 17609445872
eth0.tx_bytes: 10567699716
eth-31-0.tx_pipe_multicast_queue_cos0_packets: 7
eth-31-0.tx_pipe_multicast_queue_cos0_bytes: 738
eth-31-0.port_tx_packets: 7
eth-31-0.port_tx_bytes: 766
eth-31-0.port_tx_65_to_127_byte_packets: 5
eth-31-0.port_tx_128_to_255_byte_packets: 2
eth-31-0.port_tx_good_packets: 7
eth-31-0.port_tx_multicast_packets: 7
eth-31-0.tx_packets: 7
eth-31-0.tx_bytes: 738
eth-31-0-unix.rx_packets: 7
eth-31-0-unix.rx_bytes: 738

**Comment by tgrennan** [comment]
I'm still seeing repeated counters even after:
commit 3d16aabe629bc26ccf55da9d4f16e54f798ea440
Author: Eliot Dresselhaus <edressel@sonic.net>
Date:   Thu Jan 26 08:33:53 2017 -0800

    * only publish changed counter values

$ goes hget platina version
acbcdb9b00bf779418a3fb7de51f0ec2b04f160a

$ goes subscribe platina
eth-31-0.tx_pipe_multicast_queue_cos0_bytes: 738
eth-31-0.port_tx_packets: 7
eth-31-0.port_tx_bytes: 766
eth-31-0.port_tx_65_to_127_byte_packets: 5
eth-31-0.port_tx_128_to_255_byte_packets: 2
eth-31-0.port_tx_good_packets: 7
eth-31-0.tx_packets: 7
eth-31-0.tx_bytes: 738
eth-31-0-unix.rx_packets: 7
eth-31-0-unix.rx_bytes: 738
eth0.rx_packets: 169975936
eth0.tx_packets: 148475321
eth0.rx_bytes: 18424397730
eth0.tx_bytes: 11193190855
eth-31-0.tx_pipe_multicast_queue_cos0_bytes: 738
eth-31-0.port_tx_packets: 7
eth-31-0.port_tx_bytes: 766
eth-31-0.port_tx_65_to_127_byte_packets: 5
eth-31-0.port_tx_128_to_255_byte_packets: 2
eth-31-0.port_tx_good_packets: 7
eth-31-0.tx_packets: 7
eth-31-0.tx_bytes: 738
eth-31-0-unix.rx_packets: 7
eth-31-0-unix.rx_bytes: 738
eth0.rx_packets: 169976158
eth0.tx_packets: 148475523
eth0.rx_bytes: 18424417406
eth0.tx_bytes: 11193205593
eth-31-0.tx_pipe_multicast_queue_cos0_bytes: 738
eth-31-0.port_tx_packets: 7
eth-31-0.port_tx_bytes: 766
eth-31-0.port_tx_65_to_127_byte_packets: 5
eth-31-0.port_tx_128_to_255_byte_packets: 2
eth-31-0.port_tx_good_packets: 7
eth-31-0.tx_packets: 7
eth-31-0.tx_bytes: 738
eth-31-0-unix.rx_packets: 7
eth-31-0-unix.rx_bytes: 738
eth0.rx_packets: 169976376
eth0.tx_packets: 148475725
eth0.rx_bytes: 18424436854
eth0.tx_bytes: 11193220267
eth-31-0.tx_pipe_multicast_queue_cos0_bytes: 738
eth-31-0.port_tx_packets: 7
eth-31-0.port_tx_bytes: 766
eth-31-0.port_tx_65_to_127_byte_packets: 5
eth-31-0.port_tx_128_to_255_byte_packets: 2
eth-31-0.port_tx_good_packets: 7
eth-31-0.tx_packets: 7
eth-31-0.tx_bytes: 738
eth-31-0-unix.rx_packets: 7
eth-31-0-unix.rx_bytes: 738
eth0.rx_packets: 169976601
eth0.tx_packets: 148475930
eth0.rx_bytes: 18424456816
eth0.tx_bytes: 11193235279
eth-31-0.tx_pipe_multicast_queue_cos0_bytes: 738
eth-31-0.port_tx_packets: 7
eth-31-0.port_tx_bytes: 766
eth-31-0.port_tx_65_to_127_byte_packets: 5
eth-31-0.port_tx_128_to_255_byte_packets: 2
eth-31-0.port_tx_good_packets: 7
eth-31-0.tx_packets: 7
eth-31-0.tx_bytes: 738
eth-31-0-unix.rx_packets: 7
eth-31-0-unix.rx_bytes: 738
eth0.rx_packets: 169976818
eth0.tx_packets: 148476132
eth0.rx_bytes: 18424476192
eth0.tx_bytes: 11193249905
^C

**Comment by dlobete** [comment]
Fixed with:

commit a5b72792f03e869dbac27d0cca1dec3c2c02e501
Author: Eliot Dresselhaus <edressel@platinasystems.com>
Date:   Mon Feb 6 10:31:20 2017 -0800

    * counter update was completely wrong; try again
