### ISSUE TITLE
Test-cases failing due to convergence time(delay) issue.

### ISSUE THREAD

**Issue by RohanK-Calsoft** [platinasystems/go#148]
Build version:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.1.1

BuildID[sha1]=5046b7c2cdea8604d331dd7e5dd2fb9c85fa21ff

This issue is observed inthe following test-cases:- 
bird_bgp_peering_if_down
bird_bgp_peering_convergence

Steps of the test-case:-

Step1:- Create and configure dummy-interfaces on all invaders. Then make the necessary configuration changes in /etc/bird/bird.conf file
(The detailed files related to config of every invader are in the attachment below.)

Step2:- Restart the 'bird' service and check the 'bird' status.

Step3:- Wait for the convergence and check all the routes are converged using command "sudo birdc show route" and neighbourships using command 'sudo birdc "show protocols all bgp1"' and 'sudo birdc "show protocols all bgp2"'

Step4:- Bring the links down, and wait for a stipulated time for the routes to get disappeared and then again check the birdc routing table using the above command to verify if the changes are reflected.

Step5:- Again bring the links up and check the birdc routing table again to verify if the new changes are reflected again.

Now, the observation is when the bgp is configured, sometimes the neighbourships take a bit more time to get established than expected. The stipulated delay introduced by the playbooks is "35 secs" and it takes more than than that for neighbourships to get established (for 'bird_bgp_peering_if_down') and routes to be visible in the routing table (for 'bird_bgp_peering_convergence'). 

These cases were verified manually by running the single playbook of that particular case isolately and they were passing.The inconsistency of these test-cases is observed only in the regression.

[Bird_bgp_IF_down.docx](https://github.com/platinasystems/go/files/2768855/Bird_bgp_IF_down.docx)

**Comment by Ad9195** [comment]
in progress!

**Comment by RohanK-Calsoft** [comment]
Build version:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.2.0-rc.1

BuildID[sha1]=c98758373b4dabee19d7680c79363f5c7165d53c

Tested this on the new build, after the automation changes for the delay('for' loop implementation) were made and now both the test-cases are passing
