### ISSUE TITLE
mmu continuously drops mcast after storm

### ISSUE THREAD

**Issue by rondv** [platinasystems/go#153]
misconfigured vlan with a loop which created a packet storm, system did not recover after breaking the loop

ping packets continue to drop "mmu multicast tx cos0 drop packets"

this happened a few times during svi bringup, I don't have exact repro steps

             Name                  Address         Link    Counter                                      Count
xeth1                         02:46:8a:00:01:98     up     port rx packets                                  1
                                                           port rx bytes                                   68
                                                           port rx 65 to 127 byte packets                   1
                                                           port rx good packets                             1
                                                           port rx broadcast packets                        1
                                                           port rx 1tag vlan packets                        1
                                                           rx pipe port table packets                       1
                                                           rx pipe port table bytes                        64
xeth3                         02:46:8a:00:01:9a     up     tx pipe vlan tagged packets                      1
                                                           tx pipe unicast queue cos0 packets               1
                                                           tx pipe unicast queue cos0 bytes                64
                                                           tx pipe port table packets                       1
                                                           tx pipe port table bytes                        64
                                                           port tx packets                                  1
                                                           port tx bytes                                   68
                                                           port tx 65 to 127 byte packets                   1
                                                           port tx good packets                             1
                                                           port tx broadcast packets                        1
                                                           port tx 1tag vlan packets                        1
xeth5                         02:46:8a:00:01:9c     up     mmu multicast tx cos0 drop packets               1
                                                           mmu multicast tx cos0 drop bytes                64
xeth7                         02:46:8a:00:01:9e     up     mmu multicast tx cos0 drop packets               1
                                                           mmu multicast tx cos0 drop bytes                64
meth-0                        00:00:00:00:00:00     up     mmu multicast tx cos0 drop packets               1
                                                           mmu multicast tx cos0 drop bytes                64
meth-1                        00:00:00:00:00:00     up     port rx packets                                  1
                                                           port rx bytes                                   64
                                                           port rx 64 byte packets                          1
                                                           port rx good packets                             1
                                                           port rx broadcast packets                        1
                                                           rx pipe port table packets                       1
                                                           rx pipe port table bytes                        60
fe1-cpu                       00:00:00:00:00:00     up     tx pipe cpu vlan-redirect packets                1
                                                           tx pipe cpu vlan-redirect bytes                 64
                                                           tx pipe port table packets                       1
                                                           tx pipe port table bytes                        64

**Comment by mj073** [comment]
Please find the logs to reproduce the issue in the attachment. 
Congestion state of DUT is not consistently established, but once we establish a congestion state issue can be reproduced consistently.
[mcast_issue_screen_logs.txt](https://github.com/platinasystems/go/files/2856425/mcast_issue_screen_logs.txt)

Also I observed that, after setting multicast related buffers on DUT using cli "sudo goes vnet set fe1 mmu-mc-re-lossless-config", packets are not getting dropped.

**Comment by rondv** [comment]
tracking integration task here:
GOES Development Status (1.3 release)
