### ISSUE TITLE
panic: unix:/run/goes/socks/vnet -> unix:@

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#16]
Beta hw invader (i19)

platina@invader19:~$ /usr/bin/goes version
acbcdb9b00bf779418a3fb7de51f0ec2b04f160a

I configured autoneg and brought up a copper 100GE link to a pktgen/bcm-shell tor (i14).
I did nothing else.
After working on another project, I returned about 2h later and discovered vnet had died.

Jan 26 13:17:01 invader19 CRON[1624]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan 26 13:42:01 invader19 goes.vnetd[455]: panic: unix:/run/goes/socks/vnet -> unix:@
Jan 26 13:42:01 invader19 goes.vnetd[455]:
Jan 26 13:42:01 invader19 goes.vnetd[455]: goroutine 7 [running]:
Jan 26 13:42:01 invader19 goes.vnetd[455]: panic(0xadeb20, 0xc42015f208)
Jan 26 13:42:01 invader19 goes.vnetd[455]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Jan 26 13:42:01 invader19 goes.vnetd[455]: github.com/platinasystems/go/elib/socket.(*socket).ErrorReady(0xc42015f208, 0x0, 0x0)
Jan 26 13:42:01 invader19 goes.vnetd[455]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/socket/socket.go:221 +0x37
Jan 26 13:42:01 invader19 goes.vnetd[455]: github.com/platinasystems/go/elib/cli.(*File).ErrorReady(0xc4204ae7d0, 0x1211ac0, 0xc420f720f0)
Jan 26 13:42:01 invader19 goes.vnetd[455]:         <autogenerated>:59 +0x4a
Jan 26 13:42:01 invader19 goes.vnetd[455]: github.com/platinasystems/go/elib/iomux.(*Mux).do(0x123e760, 0xc420041350)
Jan 26 13:42:01 invader19 goes.vnetd[455]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/iomux/epoll.go:153 +0x15d
Jan 26 13:42:01 invader19 goes.vnetd[455]: github.com/platinasystems/go/elib/iomux.(*Mux).EventPoll(0x123e760)
Jan 26 13:42:01 invader19 goes.vnetd[455]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/iomux/epoll.go:166 +0xde
Jan 26 13:42:01 invader19 goes.vnetd[455]: github.com/platinasystems/go/elib/loop.(*eventLoop).eventPoller(0xc420184370, 0x1211c00, 0x123e760)
Jan 26 13:42:01 invader19 goes.vnetd[455]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:158 +0x31
Jan 26 13:42:01 invader19 goes.vnetd[455]: created by github.com/platinasystems/go/elib/loop.(*eventLoop).startPoller
Jan 26 13:42:01 invader19 goes.vnetd[455]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:161 +0x53
Jan 26 13:42:03 invader19 goes.vnetd[455]: exit status 2
Jan 26 14:17:01 invader19 CRON[1708]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

These are the cmds I did:

   77  sudo shutdown -h now
   78  ps auxw | grep "vnet"
   79  sudo goes vnet show fe1 po ph
   80  hset platina eth-32-0.media copper
   81  hset platina eth-32-0.speed auto
   82  goes hset platina eth-32-0.media copper
   83  sudo goes hset platina eth-32-0.media copper
   84  sudo goes hset platina eth-32-1.media copper
   85  sudo goes hset platina eth-32-1.speed auto
   86  sudo goes vnet show fe1 po ph | grep eth-32
   87  sudo goes vnet show fe1 po ph | head
   88  sudo less /var/log/syslog
   89  date
   90  ps -e f
   91  sudo less /var/log/syslog
   92  sudo cp -ip /var/log/syslog ~/syslog_2017_01_26_panic_socket_op.txt

When I executed command #87, it said:

platina@invader19:~$ sudo goes vnet show fe1 po ph | head
[sudo] password for platina:
vnet: dial unix /run/goes/socks/vnet: connect: connection refused

This was at:

platina@invader19:~$ date
Thu Jan 26 15:12:42 PST 2017

But it seems vnet died earlier at 13:42

Syslog saved on i19:~platina/syslog_2017_01_26_panic_socket_op.txt

**Comment by donnlee** [comment]
Next, I did 'goes stop' and 'goes start' and saw the panic after a few seconds (<30s).
```
platina@invader19:~$ sudo stop
[sudo] password for platina:
platina@invader19:~$ sudo goes start
platina@invader19:~$
```
```
platina@invader19:~$ sudo goes vnet show fe1 po ph | head
vnet: dial unix /run/goes/socks/vnet: connect: connection refused
```

syslog:
```
Jan 26 15:17:01 invader19 CRON[1770]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan 26 15:36:29 invader19 goes.uptimed[450]: killed
Jan 26 15:36:29 invader19 goes.redisd[422]: killed
Jan 26 15:36:29 invader19 goes.nld[449]: killed
Jan 26 15:36:29 invader19 goes.uptimed[450]: done
Jan 26 15:36:29 invader19 goes.nld[449]: done
Jan 26 15:36:29 invader19 goes.redisd[422]: done
Jan 26 15:36:29 invader19 goes.goes-daemons[415]: done
Jan 26 15:36:40 invader19 goes.redisd[2311]: listen: /run/goes/socks/redisd
Jan 26 15:36:40 invader19 goes.redisd[2311]: listen: [127.0.0.1%lo]:6379
Jan 26 15:36:40 invader19 goes.redisd[2311]: listen: [::1%lo]:6379
Jan 26 15:36:40 invader19 goes.redisd[2311]: listen: [192.168.101.139%eth0]:6379
Jan 26 15:36:40 invader19 goes.redisd[2311]: listen: [fe80::6eec:5aff:fe07:cdf0%eth0]:6379
Jan 26 15:37:01 invader19 goes.vnetd[2330]: panic: unix:/run/goes/socks/vnet -> unix:@
Jan 26 15:37:01 invader19 goes.vnetd[2330]:
Jan 26 15:37:01 invader19 goes.vnetd[2330]: goroutine 26 [running]:
Jan 26 15:37:01 invader19 goes.vnetd[2330]: panic(0xadeb20, 0xc42016f688)
Jan 26 15:37:01 invader19 goes.vnetd[2330]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
cket.(*socket).ErrorReady(0xc42016f688, 0x0, 0x0)
Jan 26 15:37:01 invader19 goes.vnetd[2330]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/socket/socket.go:221 +0x37
Jan 26 15:37:01 invader19 goes.vnetd[2330]: github.com/platinasystems/go/elib/cli.(*File).ErrorReady(0xc420440c80, 0x1211ac0, 0xc420ce4090)
Jan 26 15:37:01 invader19 goes.vnetd[2330]:         <autogenerated>:59 +0x4a
Jan 26 15:37:01 invader19 goes.vnetd[2330]: github.com/platinasystems/go/elib/iomux.(*Mux).do(0x123e760, 0xc420045350)
Jan 26 15:37:01 invader19 goes.vnetd[2330]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/iomux/epoll.go:153 +0x15d
Jan 26 15:37:01 invader19 goes.vnetd[2330]: github.com/platinasystems/go/elib/iomux.(*Mux).EventPoll(0x123e760)
Jan 26 15:37:01 invader19 goes.vnetd[2330]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/iomux/epoll.go:166 +0xde
Jan 26 15:37:01 invader19 goes.vnetd[2330]: github.com/platinasystems/go/elib/loop.(*eventLoop).eventPoller(0xc420196370, 0x1211c00, 0x123e760)
Jan 26 15:37:01 invader19 goes.vnetd[2330]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:158 +0x31
Jan 26 15:37:01 invader19 goes.vnetd[2330]: created by github.com/platinasystems/go/elib/loop.(*eventLoop).startPoller
Jan 26 15:37:01 invader19 goes.vnetd[2330]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:161 +0x53
Jan 26 15:37:03 invader19 goes.vnetd[2330]: exit status 2
```

**Comment by donnlee** [comment]
Ok, I think I found something.
It dies when i pipe "po phy" to 'head'.

  118  sudo goes stop
  119  sudo goes start
  120  sudo goes vnet show fe1 po m | head
  121  sudo goes vnet show ip fib
  122  sudo goes vnet show fe1 po m | head
  123  sudo goes vnet show fe1 po m | tail
  124  sudo goes vnet show fe1 po ph
  125  sudo goes vnet show fe1 po ph | head
  126  history

Everything is ok except #125.

**Comment by donnlee** [comment]
Sometimes you have to do the pipe to 'head' two times, then it crashes.
```
Jan 31 16:06:13 invader22 goes.vnetd[31850]: panic: unix:/run/goes/socks/vnet -> unix:@
```

Bug still present in:

commit 16f6f2db52218d2c926029a4d71c0c911b49e41c
Merge: 92bea95 ffad136
Author: Kevin Paul Herbert <kph@platinasystems.com>
Date:   Mon Jan 30 14:57:40 2017 -0800

    Merge commit 'ffad1365ba828769aba63ddc5a4815f2f420caf3' into HEAD

@dlobete says it'll be an easy fix (he talked to @tgrennan )

**Comment by dlobete** [comment]
pipe to linux head issue is fixed with this commit - kudos to tomg for the fix:

commit 0225a9e08495f6664b7291d1d95278fb90e11bd0
Author: Don Lobete <dlobete@platinasystems.com>
Date:   Thu Feb 2 11:21:04 2017 -0800

    Add signal handlers for SIGPIPE which is sent by linux when a write
    to a closed stream socket occurs. This could happen when a vnet command
    is issued from goes and the target process closes the socket e.g. pipe
    to head command.
    
    Signed-off-by: Don Lobete <dlobete@platinasystems.com>

**Comment by donnlee** [comment]
I will retest.

**Comment by donnlee** [comment]
Confirmed this is fixed in goes I compiled on Feb 6.
Cannot test on current tree because of issue #22

**Comment by donnlee** [comment]
I've built an ansible test for this for our regression testing framework.
