### ISSUE TITLE
/run/goes/socks/vnet group and permissions

### ISSUE THREAD

**Issue by tgrennan** [platinasystems/go#17]
/run/goes/socks/vnet should have group vnet and 0775 permissions like the other sockets.

$ ls -l /run/goes/socks
total 0
srwxrwxr-x 1 root adm  0 Jan 26 15:10 nld
srwxrwxr-x 1 root adm  0 Jan 26 15:10 redisd
srwxrwxr-x 1 root adm  0 Jan 26 15:10 redis-pub
srwxrwxr-x 1 root adm  0 Jan 26 15:10 redis-reg
srwxr-xr-x 1 root root 0 Jan 26 15:10 vnet
srwxrwxr-x 1 root adm  0 Jan 26 15:10 vnetd

**Comment by dlobete** [comment]
Fixed with

commit 0225a9e08495f6664b7291d1d95278fb90e11bd0
Author: Don Lobete <dlobete@platinasystems.com>
Date:   Thu Feb 2 11:21:04 2017 -0800

    Add signal handlers for SIGPIPE which is sent by linux when a write
    to a closed stream socket occurs. This could happen when a vnet command
    is issued from goes and the target process closes the socket e.g. pipe
    to head command.
