### ISSUE TITLE
autoneg ports sometimes do not come up after goes start

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#20]
Platina to platina ports configured for autoneg sometimes doesn't come up after goes start.

The port recovers only after issuing another "speed autoneg" setting; or with physical port tx enable disable (with debug code); or setting the autoneg restart bit (with debug code).  i.e. anything that triggers another autoneg attempt.

**Comment by dlobete** [comment]
This issue also looks to be related to doing hsets to turn on autoneg on a port via the /etc/goes/start script. Doing the hset after goes starts up doesn't reproduce the issue.

**Comment by fszyang** [comment]
I can get it to fail without restarting goes by doing this.

- hset port to 100g
- hset port to auto
- check if link is up
repeat

The other end of the link is another invader that's set to auto.
When the link doesn't come up, doing another hset port to auto will bring it back up.

**Comment by jasonlpang** [comment]
What is the delay between the hset to 100G and the hset to auto?

**Comment by fszyang** [comment]
1 second

**Comment by fszyang** [comment]
Retesting with 3 second delay in between.   Running OK so far.

**Comment by jasonlpang** [comment]
Can you please also try:
hset disable port
hset port to auto
hset enable port
check if link is up
hset disable port
hset port to 100g
hset enable port
check if link is up
repeat
-jason

**Comment by dlobete** [comment]
I've seen autoneg take over 1 second to settle sometimes. Not sure this is
the same case as the startup issue. We init TH ports to 100g and then set
to auto in /etc/goes/start.
Don.

**Comment by fszyang** [comment]
Took longer, but failed with 3 second delays also

**Comment by jasonlpang** [comment]
There’s a difference between the two setups:

Don’s setup is two ports on the same switch connected together.  So when goes starts both ports will transition from auto neg off to on.

Frank’s setup is two ports on different switches connected together.  Goes start/stop and hset autoneg on/off are only done on one side.  The peer side is live the whole time.  

There might be two issues. It could be that /etc/goes/start config is being executed too early and separately there may be some interaction with the live peer and turning auto neg on/off while keeping the port enabled.

It may be interesting on Frank’s setup to test:
- goes start/stop without /etc/goes/start
- use hset after goes start to enable auto neg but disable the port first before the hset

-jason

**Comment by dlobete** [comment]
Jason,
What do you mean by "disable the port" ?
Don.

**Comment by jasonlpang** [comment]
By disable I mean to do SetEnable( _,false), then turn AN on, then SetEnable(_,true).  Not sure if we have an hset command to trigger SetEnable.  In any case, disabling the 1GKX setting is probably worth trying first.

-jason

**Comment by dlobete** [comment]
Right - we don't have a redis-level command for enable/disable which is why
I wanted to clarify. I believe the sdk does the sequence your are talking
about i.e. disable/change-speed/enable correct?
Given that, I'm not sure how valid flipping between fixed-speed and autoneg
is for us at the moment. And doubt a customer would do that - the more
obvious issue is we have to make /etc/goes/start work at startup since all
customers would probably use it.
Don.

**Comment by dlobete** [comment]
Closed with:

commit 133016888322e83fa94d542f63015143c370c736
Author: Don Lobete <dlobete@platinasystems.com>
Date:   Mon Feb 13 11:40:26 2017 -0800

    TO match sdk and stabilize autoneg make autoneg-error timer value 0 (which we think means
    make the timer unlimited)
    
    Signed-off-by: Don Lobete <dlobete@platinasystems.com>
