### ISSUE TITLE
deleting dummy interface causes panic

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#26]
Code up-to-date with today's fix which seem to fix #23 (and maybe #22 and #25), however when I delete the dummy interface it panics (sometimes "ip link del dummy0" also causes it.

root@invader1:~# goes vnet show ip fib
 Table                   Destination           Adjacency

root@invader1:~# ip link set up dev eth-1-0
root@invader1:~# ip add add 1.1.1.1/23 dev eth-1-0

root@invader1:~# goes vnet show ip fib
 Table                   Destination           Adjacency
     0                    1.1.0.0/23  3: glean eth-1-0
     0                    1.1.1.1/32  4: local eth-1-0

root@invader1:~# ip link add name dummy0 type dummy
root@invader1:~# ip link set up dummy0
root@invader1:~# ip add add 3.3.3.3/24 dev dummy0

root@invader1:~# goes vnet show ip fib
 Table                   Destination           Adjacency
     0                    1.1.0.0/23  3: glean eth-1-0
     0                    1.1.1.1/32  4: local eth-1-0
     0                    3.3.3.0/24  2: punt

root@invader1:~# ip link del dummy0

- causes

Mar  8 14:46:04 invader1 goes.vnetd[19385]: not found: goroutine 36 [running]:
Mar  8 14:46:04 invader1 goes.vnetd[19385]: runtime/debug.Stack(0x0, 0x0, 0x0)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x80
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc8200f4b00)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:128 +0xa2
Mar  8 14:46:04 invader1 goes.vnetd[19385]: panic(0xb94ea0, 0xc82000b170)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /usr/local/go/src/runtime/panic.go:426 +0x4e9
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).ip4_fib_add_del(0xc8201f8000, 0xc800000000, 0xc82000b118, 0x100000002)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/fib.go:279 +0x1a0
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).(github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.ip4_fib_add_del)-fm(0xc800000000, 0xc82000b118, 0x100000002)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/fib.go:49 +0x4c
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/vnet/ip4.(*Fib).addDel(0xc820486160, 0xc8201d0000, 0xc82000b118, 0x100000002, 0xb4ac80)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:176 +0xb9
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/vnet/ip4.(*Main).addDelRoute(0xc8201d0000, 0xc820cdf3c0, 0x200000000, 0x1, 0xdcfc80, 0x0, 0x0)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:367 +0x1cf
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.addDelRoute)-fm(0xc820cdf3c0, 0x200000000, 0x1, 0xc81ff82e8e, 0x0, 0x0)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/vnet/ip4/package.go:24 +0x51
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/vnet/unix.(*dummyInterface).addDelDummyPuntPrefixes(0xc820b06060, 0xc8201a8480, 0xc800002e01)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:93 +0x30b
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc8208a8060)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:283 +0x813
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc8208a8390)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x135
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc8200f4b00, 0xc8208a8390)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x48
Mar  8 14:46:04 invader1 goes.vnetd[19385]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc8200f4b00, 0x7f038a8753a0, 0xc8200f5048)
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x81
Mar  8 14:46:04 invader1 goes.vnetd[19385]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Mar  8 14:46:04 invader1 goes.vnetd[19385]:         /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x120

**Comment by donnlee** [comment]
In my tests, adding dummy0 (with IP address) also causes this.

**Comment by stigt** [comment]
I believe this issue is fix by this commit -https://github.com/platinasystems/fe1/commit/b38eb31e5e8d5bc251d965c08597ba33785cabd5

**Comment by donnlee** [comment]
Fix verified.  I found a new issue that I opened today, #30 

Closing this issue.

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader44:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader44:/home/rohan# goes version
v1.1.1

1) Added a dummy interface and checked the 'goes' table.

root@invader44:~# ip link add name dummy0 type dummy
root@invader44:~# ip link set up dummy0
root@invader44:~# ip add add 3.3.3.3/24 dev dummy0

root@invader44:~# goes vnet show ip fib
Table Destination Adjacency
0 1.1.0.0/23 3: glean xeth1
0 1.1.1.1/32 4: local xeth1
0 3.3.3.0/24 2: punt

2). Deleted the dummy interface 

root@invader44:~# ip link del dummy0
root@invader44:~#

root@invader44:/home/rohan# goes status
GOES status
---------------------------
  Mode            - XETH
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK

Repeated "step 2)" couple of times.

**Result:-** No panic observed .Works fine on the new build, version-v.1.1.1
