### ISSUE TITLE
panic: tuntap ioctl SETIFHWADDR: cannot assign requested address: 00:00:00:00:00:00

### ISSUE THREAD

**Issue by jasonlpang** [platinasystems/go#36]
I'm seeing the following panic about 1 out of 10 times with "./goes-platina-mk1 install".  I'm at top of tree with go and fe1:
go: commit 0bd1317813e7eab4b164af12474bf7db742e8abe
fe1: commit 87d0ed69f629bf509830e2a0be053a603dd36bab

Dec  8 18:05:09 platina systemd[1]: Reloading.
Dec  8 18:05:09 platina systemd[1]: Started ACPI event daemon.
Dec  8 18:05:09 platina systemd[1]: Listening on ACPID Listen Socket.
Dec  8 18:05:09 platina systemd[1]: Activated swap /dev/disk/by-uuid/46931bab-e3fb-4f43-be65-7575289bf444.
Dec  8 18:05:09 platina systemd[1]: Activated swap /dev/sda5.
Dec  8 18:05:09 platina systemd[1]: Activated swap /dev/disk/by-id/ata-SanDisk_SD8SMAT128G1122_162823401251-part5.
Dec  8 18:05:09 platina systemd[1]: Activated swap /dev/disk/by-id/wwn-0x5001b444a409787f-part5.
Dec  8 18:05:09 platina goes.redisd[1916]: listen: /run/goes/socks/redisd
Dec  8 18:05:09 platina goes.redisd[1916]: listen: [127.0.0.1%lo]:6379
Dec  8 18:05:09 platina goes.redisd[1916]: listen: [::1%lo]:6379
Dec  8 18:05:09 platina goes.redisd[1916]: listen: [192.168.101.213%eth0]:6379
Dec  8 18:05:09 platina goes.redisd[1916]: listen: [fe80::205:64ff:febb:bb84%eth0]:6379
Dec  8 18:05:11 platina goes.i2cd[1926]: listen OKAY
Dec  8 18:05:11 platina goes.vnetd[1932]: panic: tuntap ioctl SETIFHWADDR: cannot assign requested address: 00:00:00:00:00:00
Dec  8 18:05:11 platina goes.vnetd[1932]: 
Dec  8 18:05:11 platina goes.vnetd[1932]: goroutine 1 [running]:
Dec  8 18:05:11 platina goes.vnetd[1932]: panic(0xa75680, 0xc42006e540)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet.(*Vnet).NewSwIf(0xc4200eab00, 0x100000001, 0xc42086d4d8)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/interface.go:161 +0x15e
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet.(*Vnet).RegisterAndProvisionHwInterface(0xc4200eab00, 0x7f498fba47e8, 0xc4201f4500, 0x7f498fba4701, 0xb8c7fd, 0xc, 0xc42086d5c8, 0x3, 0x3, 0xc4203c54fb, ...)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/interface.go:399 +0x23f
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet/ethernet.RegisterInterface(0xc4200eab00, 0x12ae800, 0xc4201f4500, 0xc4201f4808, 0xb8c7fd, 0xc, 0xc42086d5c8, 0x3, 0x3)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/ethernet/interface.go:159 +0xed
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet/devices/ethernet/ixge.(*dev).vnetInit(0xc4201f4500)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/ixge/vnet.go:36 +0x282
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet/devices/ethernet/ixge.(*dev).Init(0xc4201f4500)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/ixge/init.go:145 +0x278
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/elib/hw/pci.DiscoverDevices(0x0, 0x0)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/hw/pci/linux_pci.go:199 +0x69d
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet/devices/bus/pci.(*pciDiscover).Init(0xc42018ad90, 0x4, 0x6)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/devices/bus/pci/pci.go:14 +0x22
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet.(*packageMain).InitPackages(0xc4200eb4c0, 0xc4200de540, 0x0)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/package.go:156 +0x30b
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet.(*Vnet).configure(0xc4200eab00, 0xc4200de540, 0xbff110, 0xc4201c5a90)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/vnet.go:43 +0x64
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet.(*Vnet).Run.func1(0xc4200eab00)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/vnet.go:58 +0xd1
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/elib/loop.(*Loop).callInitHooks(0xc4200eab00)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/loop.go:389 +0x5d
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/elib/loop.(*Loop).Run(0xc4200eab00)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/loop.go:441 +0xf0
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/vnet.(*Vnet).Run(0xc4200eab00, 0xc4200de540, 0x1, 0x1)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/vnet.go:62 +0xab
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/internal/goes/cmd/vnetd.(*cmd).Main(0xc4200eab00, 0xc42006e160, 0x0, 0x0, 0x0, 0x0)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/internal/goes/cmd/vnetd/vnetd.go:116 +0x689
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/internal/goes.(mainer).Main-fm(0xc42006e160, 0x0, 0x0, 0xc420158120, 0xc420045d10)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/internal/goes/goes.go:223 +0x4d
Dec  8 18:05:11 platina goes.vnetd[1932]: github.com/platinasystems/go/internal/goes.ByName.Main(0xc4201306c0, 0xc42006e160, 0x0, 0x0, 0x0, 0x0)
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/internal/goes/goes.go:192 +0x588
Dec  8 18:05:11 platina goes.vnetd[1932]: main.main()
Dec  8 18:05:11 platina goes.vnetd[1932]:         /home/jpang/gopath/src/github.com/platinasystems/go/main/goes-platina-mk1/main.go:14 +0x4c
Dec  8 18:05:11 platina goes.vnetd[1932]: exit status 2

**Comment by stigt** [comment]
I also see this quite often, but figured it should go away when we switch to sriov.  For some reason the the ixge interfaces are going through the tuntap code for SwIfAddDel() and trying to assign a mac address of all zeros.  I have a hack to work around it by skipping all non tuntap interfaces:

```
diff --git a/vnet/unix/tuntap.go b/vnet/unix/tuntap.go
index 74da17e..556bff3 100644
--- a/vnet/unix/tuntap.go
+++ b/vnet/unix/tuntap.go
@@ -241,6 +241,10 @@ func (m *Main) SwIfAddDel(v *vnet.Vnet, si vnet.Si, isDel bool) (err error) {
        }
 
        copy(intf.name[:], si.Name(v))
+       if intf.name[0] != 'e' {
+               fmt.Println("SwIfAddDel", intf.name)
+               return
+       }
 
        if err = intf.open(); err != nil {
```

**Comment by jasonlpang** [comment]
closing, since we moved to SRIOV
