### ISSUE TITLE
vnet crashes when adding 7th path to ECMP

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#44]
Version: 74dfc8bf92f27aeb031d4827a534673c52f78afe
(also included commit c7d5054515784cb33860ef15aa5e5f4d17fdd4ea in fe1)

Always reproducible. 

10.0.0.2, 10.0.2.2, 10.0.4.2, ... ,10.0.30.2 have static arp set up.
e.g. 10.0.0.2 dev eth-0-0 lladdr 02:46:8a:00:03:ae PERMANENT

Steps to reproduce:
fyang@invader7:$ sudo ip route add 100.0.0.0/24 via 10.0.0.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.2.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.4.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.6.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.8.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.10.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.12.2   <---- vnet crashed

Restart goes and retry with different ECMP paths
fyang@invader7:$ sudo ip route add 100.0.0.0/24 via 10.0.8.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.10.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.12.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.14.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.16.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.18.2
fyang@invader7:$ sudo ip route app 100.0.0.0/24 via 10.0.20.2  <---- vnet crashed

Syslog:
Apr 28 12:24:29 invader7 goes.vnetd[31046]: unknown multipath adjacency: goroutine 52 [running]:
Apr 28 12:24:29 invader7 goes.vnetd[31046]: runtime/debug.Stack(0xc420869a40, 0xa54b20, 0xc420ab4990)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc42018a000)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x91
Apr 28 12:24:29 invader7 goes.vnetd[31046]: panic(0xa54b20, 0xc420ab4990)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /usr/local/go/src/runtime/panic.go:458 +0x243
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/vnet/ip.(*multipathAdjacency).free(0xc420ca6530, 0xc42021e068)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip/adjacency.go:662 +0x290
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/vnet/ip.(*Main).AddDelNextHop(0xc42021e068, 0x25a, 0x1000000b3, 0xc42009
8b28)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip/adjacency.go:537 +0x2ad
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/vnet/ip4.(*Main).AddDelRouteNextHop(0xc42021e000, 0xc420c23bf0, 0xc420c2
3c00, 0x34020c0000, 0x1, 0xc4201880f0)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/ip4/fib.go:429 +0x1d8
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/vnet/unix.(*Main).ip4RouteMsg(0xc420224500, 0xc420bb11e0, 0xc42007e401,
0xc4203f5d40, 0xc420869e70)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:542 +0x29e
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc420b0c840)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:345 +0x47e
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc4204d6cc0)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc42018a000, 0xc4204d6cc0)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
Apr 28 12:24:29 invader7 goes.vnetd[31046]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc42018a000, 0x12d7280, 0xc42018a548)
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
Apr 28 12:24:29 invader7 goes.vnetd[31046]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Apr 28 12:24:29 invader7 goes.vnetd[31046]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
Apr 28 12:24:29 invader7 goes.vnetd[31046]: done

**Comment by stigt** [comment]
The following patch individually hashes the nexthops rather than make any assumptions on how data structures are laid out in memory for a slice of slices.  I'd like to have Eliot review if this is an acceptable patch.

diff --git a/vnet/ip/adjacency.go b/vnet/ip/adjacency.go
index 59e762b..6976302 100644
--- a/vnet/ip/adjacency.go
+++ b/vnet/ip/adjacency.go
@@ -204,7 +204,9 @@ func (m *multipathMain) HashResize(newCap uint, rs 
 func (a nextHopVec) HashKey(s *elib.HashState) {
-       s.HashPointer(unsafe.Pointer(&a[0]), uintptr(a.Len())*unsafe.Sizeof(a[0]))
+       for _, nh := range a {
+               s.HashUint64(uint64(nh.Adj), uint64(nh.Weight), 0, 0)
+       }
 }


Using this patch I was able to add 16 ECMP routes:

     0                 10.100.0.0/24    1337: rewrite eth-20-0 IP4: 02:46:8a:00:02:b7 -> 02:46:8a:00:05:da 1337-1337, 1 x 41
                                        1338: rewrite eth-20-0 IP4: 02:46:8a:00:02:b7 -> 02:46:8a:00:05:da 1338-1338, 1 x 42
                                        1339: rewrite eth-20-0 IP4: 02:46:8a:00:02:b7 -> 02:46:8a:00:05:da 1339-1339, 1 x 43
                                        1340: rewrite eth-20-0 IP4: 02:46:8a:00:02:b7 -> 02:46:8a:00:05:da 1340-1340, 1 x 44
                                        1341: rewrite eth-20-0 IP4: 02:46:8a:00:02:b7 -> 02:46:8a:00:05:da 1341-1341, 1 x 45
                                        1342: rewrite eth-20-0 IP4: 02:46:8a:00:02:b7 -> 02:46:8a:00:05:da 1342-1342, 1 x 46
                                        1343: rewrite eth-21-0 IP4: 02:46:8a:00:02:b8 -> 02:46:8a:00:05:db 1343-1343, 1 x 47
                                        1344: rewrite eth-21-0 IP4: 02:46:8a:00:02:b8 -> 02:46:8a:00:05:db 1344-1344, 1 x 48
                                        1345: rewrite eth-21-0 IP4: 02:46:8a:00:02:b8 -> 02:46:8a:00:05:db 1345-1345, 1 x 49
                                        1346: rewrite eth-21-0 IP4: 02:46:8a:00:02:b8 -> 02:46:8a:00:05:db 1346-1346, 1 x 50
                                        1347: rewrite eth-21-0 IP4: 02:46:8a:00:02:b8 -> 02:46:8a:00:05:db 1347-1347, 1 x 51
                                        1348: rewrite eth-22-0 IP4: 02:46:8a:00:02:b9 -> 02:46:8a:00:05:dc 1348-1348, 1 x 52
                                        1349: rewrite eth-22-0 IP4: 02:46:8a:00:02:b9 -> 02:46:8a:00:05:dc 1349-1349, 1 x 53
                                        1350: rewrite eth-22-0 IP4: 02:46:8a:00:02:b9 -> 02:46:8a:00:05:dc 1350-1350, 1 x 54
                                        1351: rewrite eth-22-0 IP4: 02:46:8a:00:02:b9 -> 02:46:8a:00:05:dc 1351-1351, 1 x 55
                                        1352: rewrite eth-22-0 IP4: 02:46:8a:00:02:b9 -> 02:46:8a:00:05:dc 1352-1352, 1 x 56

**Comment by stigt** [comment]
Fixed with the following commit:https://github.com/platinasystems/go/commit/cf4a253399762d13a97a5f7012fbc2934fa18c6b
