### ISSUE TITLE
Cannot assign same IP to two different containers/namespaces

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#51]
Container "gobgp_gobgp1_1" owns eth-30-1 with ip 192.168.217.1/32:

vnet sho ip fib:

```
     2              192.168.217.0/24     273: glean eth-32-1
     2              192.168.217.2/32     274: local eth-32-1
                                        tx pipe packets             6461
                                        tx pipe bytes             659022
     3              192.168.217.0/24     581: glean eth-30-1
     3              192.168.217.1/32     255: local eth-30-1
     3              192.168.217.2/32     256: rewrite eth-30-1 IP4: 6c:ec:5a:07:c8:d7 -> 6c:ec:5a:07:c8:d9
```

Note the line:

```
     3              192.168.217.1/32     255: local eth-30-1
```

This is fine.

Now assign same IP to a different container named "gobgp_gobgp10_1", which owns eth-1-1:

```
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID10 ip addr del 192.168.217.1/24 dev en100
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID10 ip addr add 192.168.217.1/24 dev en100
```

vnet sho ip fib:

```
     2              192.168.217.0/24     273: glean eth-32-1
     2              192.168.217.2/32     274: local eth-32-1
                                        tx pipe packets             6461
                                        tx pipe bytes             659022
     3              192.168.217.2/32     256: rewrite eth-30-1 IP4: 6c:ec:5a:07:c8:d7 -> 6c:ec:5a:07:c8:d9
     4              192.168.217.0/24     255: glean eth-1-1
     4              192.168.217.1/32     581: local eth-1-1
```

Note the line:
```
     4              192.168.217.1/32     581: local eth-1-1
```

Do you see how 192.168.217.1/32 (table 3) for eth-30-1 is now missing?

I expected to see two 192.168.217.1/32 entries:  One for table 3 (eth-30-1) and another for table 4 (eth-1-1)

If I use unique ip addresses, then everything is happy:

```
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID1 ip addr del 192.168.217.1/24 dev en100
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID1 ip addr add 192.168.217.1/24 dev en100
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID10 ip addr del 192.168.217.1/24 dev en100
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID10 ip addr add 192.168.222.222/24 dev en100
donn@invader17:~/workspace/docker/gobgp$ sudo goes vnet sho ip fib | less
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID1 ip addr del 192.168.217.1/24 dev en100
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID1 ip addr add 192.168.217.1/24 dev en100
donn@invader17:~/workspace/docker/gobgp$ sudo goes vnet sho ip fib | less
```

fib:

```
     2              192.168.217.0/24     273: glean eth-32-1
     2              192.168.217.2/32     274: local eth-32-1
                                        tx pipe packets             6461
                                        tx pipe bytes             659022
     3              192.168.217.0/24     275: glean eth-30-1
     3              192.168.217.1/32     257: local eth-30-1
     3              192.168.217.2/32     256: rewrite eth-30-1 IP4: 6c:ec:5a:07:c8:d7 -> 6c:ec:5a:07:c8:d9
     4              192.168.222.0/24     255: glean eth-1-1
     4            192.168.222.222/32     581: local eth-1-1
```

Note the `local eth-x-y` lines.

Supporting data:

```
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns list-id
nsid 0
nsid 1 (iproute2 netns name: 23607)
nsid 2 (iproute2 netns name: 11905)
nsid 3 (iproute2 netns name: 24213)
```

Note also that the nsid's in linux don't match table-id in `vnet sho ip fib`.  This is weird.

```
donn@invader17:~/workspace/docker/gobgp$ echo $CONTAINER_PID1
23607
donn@invader17:~/workspace/docker/gobgp$ echo $CONTAINER_PID10
24213
```

```
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID1 ip addr  sho en100
179: en100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 6c:ec:5a:07:c8:d7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.217.1/24 scope global en100
       valid_lft forever preferred_lft forever
    inet6 fe80::6eec:5aff:fe07:c8d7/64 scope link
       valid_lft forever preferred_lft forever

donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID10 ip addr  sho en100
150: en100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 6c:ec:5a:07:c8:ba brd ff:ff:ff:ff:ff:ff
    inet 192.168.222.222/24 scope global en100
       valid_lft forever preferred_lft forever
    inet6 fe80::6eec:5aff:fe07:c8ba/64 scope link
       valid_lft forever preferred_lft forever
```

Linux nsid 1 (owner of eth-30-1), appears in vnet as table-id 3
Linux nsid 2 (owner of eth-32-1), appears in vnet as table-id 2
Linux nsid 3 (owner of eth-1-1), appears in vnet as table-id 4

**Comment by donnlee** [comment]
Here's another trial in which the dupe IP seems to be ignored by goes.

Clean slate. goes restart

vnet fib:

Move interfaces to containers:  eth-30-1 to container gobgp1, eth-32-1 to container gobgp2.
```
     2              192.168.217.0/24     255: glean eth-30-1
     2              192.168.217.1/32     256: local eth-30-1
     3              192.168.217.0/24     257: glean eth-32-1
     3              192.168.217.2/32     258: local eth-32-1
```

Now move eth-1-1 to container gobgp10, with SAME ip as gobgp1:
```
donn@invader17:~/workspace/docker/gobgp$ sudo ./move_interface.sh eth-1-1 gobgp_gobgp10_1 192.168.217.1/24
directory check: ok
symlink for pid 25235 exists.
nsid 3 (iproute2 netns name: 25235)
nsid check: ok
229: eth-1-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 6c:ec:5a:07:c8:ba brd ff:ff:ff:ff:ff:ff
```

vnet fib:
```
     2              192.168.217.0/24     255: glean eth-30-1
     2              192.168.217.1/32     256: local eth-30-1
     3              192.168.217.0/24     257: glean eth-32-1
     3              192.168.217.2/32     258: local eth-32-1
```

Note that eth-1-1 is absent.  It should be in the list.

This shows gobgp10 is configured with 192.168.217.1/24:
```
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID10 ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
193: eth0@if194: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:13:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.3/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:3/64 scope link
       valid_lft forever preferred_lft forever
229: en100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 6c:ec:5a:07:c8:ba brd ff:ff:ff:ff:ff:ff
    inet 192.168.217.1/24 scope global en100
       valid_lft forever preferred_lft forever
    inet6 fe80::6eec:5aff:fe07:c8ba/64 scope link
       valid_lft forever preferred_lft forever
donn@invader17:~/workspace/docker/gobgp$
```

And so is gobgp1:
```
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns exec $CONTAINER_PID1 ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
258: en100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 6c:ec:5a:07:c8:d7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.217.1/24 scope global en100
       valid_lft forever preferred_lft forever
    inet6 fe80::6eec:5aff:fe07:c8d7/64 scope link
       valid_lft forever preferred_lft forever
191: eth0@if192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:2/64 scope link
       valid_lft forever preferred_lft forever
```

output of 'ip monitor':
```
[nsid 3][NETCONF]ipv4 dev if229 forwarding on rp_filter off mc_forwarding off proxy_neigh off ignore_routes_with_linkdown off
[nsid 3][NETCONF]ipv6 dev if229 forwarding off proxy_neigh off ignore_routes_with_linkdown off
[nsid 3][LINK]229: eth-1-1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default
    link/ether 6c:ec:5a:07:c8:ba brd ff:ff:ff:ff:ff:ff
[nsid 3][LINK]229: en100: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default
    link/ether 6c:ec:5a:07:c8:ba brd ff:ff:ff:ff:ff:ff
[nsid 3][NETCONF]ipv4 dev eth-1-1 forwarding on rp_filter off mc_forwarding off proxy_neigh off ignore_routes_with_linkdown off
[nsid 3][NETCONF]ipv6 dev eth-1-1 forwarding off proxy_neigh off ignore_routes_with_linkdown off
[nsid 3][ADDR]229: eth-1-1    inet 192.168.217.1/24 scope global en100
       valid_lft forever preferred_lft forever
[nsid 3][ROUTE]local 192.168.217.1 dev eth-1-1  table local  proto kernel  scope host  src 192.168.217.1
[nsid 3][LINK]229: en100: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default
    link/ether 6c:ec:5a:07:c8:ba brd ff:ff:ff:ff:ff:ff
[nsid 3][ROUTE]192.168.217.0/24 dev eth-1-1  proto kernel  scope link  src 192.168.217.1
[nsid 3][ROUTE]broadcast 192.168.217.0 dev eth-1-1  table local  proto kernel  scope link  src 192.168.217.1
[nsid 3][ROUTE]broadcast 192.168.217.255 dev eth-1-1  table local  proto kernel  scope link  src 192.168.217.1
[nsid 3][ROUTE]ff00::/8 dev eth-1-1  metric 256  pref medium
[nsid 3][ROUTE]fe80::/64 dev eth-1-1  proto kernel  metric 256  pref medium
[nsid 3][LINK]229: en100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default
    link/ether 6c:ec:5a:07:c8:ba brd ff:ff:ff:ff:ff:ff
[nsid 3][ADDR]229: eth-1-1    inet6 fe80::6eec:5aff:fe07:c8ba/64 scope link
       valid_lft forever preferred_lft forever
[nsid 3][ROUTE]local fe80::6eec:5aff:fe07:c8ba dev lo  proto kernel  metric 0  pref medium
[nsid current][NEIGH]172.19.0.3 dev br-c381713c42fa lladdr 02:42:ac:13:00:03 STALE
[nsid 3][NEIGH]172.19.0.1 dev if193 lladdr 02:42:71:e0:8f:eb REACHABLE
```
Linux nsid 3 is gobgp10 (eth-1-1).

```
donn@invader17:~/workspace/docker/gobgp$ sudo ip netns list-id
nsid 0
nsid 1 (iproute2 netns name: 25159)
nsid 2 (iproute2 netns name: 25236)
nsid 3 (iproute2 netns name: 25235)
donn@invader17:~/workspace/docker/gobgp$ echo $CONTAINER_PID10
25235

**Comment by dlobete** [comment]
Reproduced and proposed fix under review.

**Comment by dlobete** [comment]
Fixed with commit
Commit: 9d4d26d73407b72e46a6c10142ee951e9a7afd1e

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.1.1


1. Created two container & moved two different interfaces and assigned them same IP and observed the FIB:

root@invader42:/# docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
stigt/debian-quagga   latest              9483ab8a2759        6 months ago        257MB


**1st container:-**
root@invader42:/# docker run --rm --privileged=true -P --hostname=R1 --name=R1 -d -v $(pwd)/volumes/quagga/R1:/etc/quagga stigt/debian-quagga:latest
`8960b2bc8301a2ab9367337cc4ace0bd1c3fe2b0f35339119b96381bea195c4e`


root@invader42:/# docker ps -a
CONTAINER ID        IMAGE                        COMMAND              CREATED              STATUS              PORTS                                                                                                                        NAMES
8960b2bc8301        stigt/debian-quagga:latest   "/root/startup.sh"   About a minute ago   Up About a minute   0.0.0.0:32777->179/tcp, 0.0.0.0:32776->2601/tcp, 0.0.0.0:32775->2604/tcp, 0.0.0.0:32774->2605/tcp, 0.0.0.0:32773->5201/tcp   R1


root@invader42:/# sudo ./docker_move.sh up R1 xeth5 192.168.120.5/24
root@invader42:/#

root@invader42:/# goes vnet show ip fib | grep 192.168.120.
       28519              192.168.120.0/24       3: glean xeth5
       28519              192.168.120.5/32     327: local xeth5

**2nd container:-**
root@invader42:/# docker run --rm --privileged=true -P --hostname=R2 --name=R2 -d -v $(pwd)/volumes/quagga/R2:/etc/quagga stigt/debian-quagga:latest
`7eb66a4e939a5e344b85317c5f0a38e0bf91cf4d879d993f4c7edec06b96e3d7`
root@invader42:/#


root@invader42:/# docker ps -a
CONTAINER ID        IMAGE                        COMMAND              CREATED             STATUS              PORTS                                                                                                                        NAMES
7eb66a4e939a        stigt/debian-quagga:latest   "/root/startup.sh"   9 seconds ago       Up 8 seconds        0.0.0.0:32782->179/tcp, 0.0.0.0:32781->2601/tcp, 0.0.0.0:32780->2604/tcp, 0.0.0.0:32779->2605/tcp, 0.0.0.0:32778->5201/tcp   R2
8960b2bc8301        stigt/debian-quagga:latest   "/root/startup.sh"   3 minutes ago       Up 3 minutes        0.0.0.0:32777->179/tcp, 0.0.0.0:32776->2601/tcp, 0.0.0.0:32775->2604/tcp, 0.0.0.0:32774->2605/tcp, 0.0.0.0:32773->5201/tcp   R1
root@invader42:/#


root@invader42:/# sudo ./docker_move.sh up R2 xeth7 192.168.120.5/24
root@invader42:/#

root@invader42:/# goes vnet show ip fib | grep 192.168.120.
       28519              192.168.120.0/24       3: glean xeth5
       28519              192.168.120.5/32     327: local xeth5
       28876              192.168.120.0/24       4: glean xeth7
       28876              192.168.120.5/32     328: local xeth7
root@invader42:/#

root@invader42:/# ./docker_move.sh down R2 xeth7
root@invader42:/#
root@invader42:/# ./docker_move.sh down R1 xeth5
root@invader42:/#

root@invader42:/# docker stop 7eb66a4e939a
7eb66a4e939a
root@invader42:/#
root@invader42:/# docker stop 8960b2bc8301
8960b2bc8301
root@invader42:/#


2. Created two different name spaces & assigned two different interfaces and observed the FIB entry.

root@invader42:/# ip netns add blue
root@invader42:/# ip link set xeth7 netns blue
root@invader42:/# ip netns set blue 15
root@invader42:/# ip netns exec blue ip link set up xeth7
root@invader42:/# ip netns exec blue ip add add 10.1.0.2/24 dev xeth7
root@invader42:/#

root@invader42:/# ip netns list
blue (id: 15)
root@invader42:/#
root@invader42:/# goes vnet show ip fib | grep 10.1.0
        blue                   10.1.0.0/24       3: glean xeth7
        blue                   10.1.0.2/32     345: local xeth7
root@invader42:/#

root@invader42:/# ip netns add red
root@invader42:/# ip link set xeth9 netns red
root@invader42:/# ip netns set red 16
root@invader42:/# ip netns exec red ip link set up xeth9
root@invader42:/# ip netns exec red ip add add 10.1.0.2/24 dev xeth9
root@invader42:/#

root@invader42:/# ip netns list
red (id: 16)
blue (id: 15)
root@invader42:/#
root@invader42:/# goes vnet show ip fib | grep 10.1.0
        blue                   10.1.0.0/24       3: glean xeth7
        blue                   10.1.0.2/32     345: local xeth7
         red                   10.1.0.0/24       4: glean xeth9
         red                   10.1.0.2/32     346: local xeth9

root@invader42:/# ip netns del red
root@invader42:/# ip netns del blue
root@invader42:/#
root@invader42:/# goes restart

**Result**:- Issue not observed on the latest build(v1.1.1)
