### ISSUE TITLE
secondary IP address is "remembered" when interface is moved to a namespace

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#55]
This issue may be related to issue #54 since that is also triggered by a secondary address.

- Primary and secondary on eth-0-0 in default namespace:
```
ip add sh eth-0-0
657: eth-0-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:46:8a:00:02:a3 brd ff:ff:ff:ff:ff:ff
    inet 10.15.0.1/24 scope global eth-0-0
       valid_lft forever preferred_lft forever
    inet 10.16.0.1/24 scope global eth-0-0
       valid_lft forever preferred_lft forever
    inet6 fe80::46:8aff:fe00:2a3/64 scope link 
       valid_lft forever preferred_lft forever
```
```
root@invader1:/home/stig# goes vnet show ip fib  | grep eth-0-0
     0                  10.15.0.0/24       5: glean eth-0-0
     0                  10.15.0.1/32       6: local eth-0-0
     0                  10.16.0.0/24       3: glean eth-0-0
     0                  10.16.0.1/32       4: local eth-0-0

```
- Move eth-0-0 to namespace red:
```
root@invader1:/home/stig# ip netns add red
root@invader1:/home/stig# ip link set eth-0-0 netns red
root@invader1:/home/stig# ip netns set red 20
root@invader1:/home/stig# 
root@invader1:/home/stig# goes vnet show ip fib  | grep eth-0-0
root@invader1:/home/stig# 
root@invader1:/home/stig# ip netns exec red ip add sh
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
753: eth-0-0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 02:46:8a:00:02:a3 brd ff:ff:ff:ff:ff:ff
```
- At this point the fib no longer "knows" about eth-0-0 and eth-0-0 is down in namespace red with no IP addresses.  Now bring up eth-0-0:

```
root@invader1:/home/stig# ip netns exec red ip link set up eth-0-0
root@invader1:/home/stig# goes vnet show ip fib  | grep eth-0-0
     2                  10.16.0.0/24      57: glean eth-0-0
     2                  10.16.0.1/32      58: local eth-0-0
root@invader1:/home/stig# 
root@invader1:/home/stig# ip netns exec red ip add sh
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
753: eth-0-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:46:8a:00:02:a3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::46:8aff:fe00:2a3/64 scope link 
       valid_lft forever preferred_lft forever
```
- After bring up eth-0-0 in namespace red, vnet has re-added connected route for the secondary even though no IP addresses are configured on eth-0-0.

**Comment by stigt** [comment]
No long happens with 6/26 build.

```
root@invader1:~# ip netns add net1
root@invader1:~# ip link set eth-0-0 netns net1
root@invader1:~# ip netns set net1 10
root@invader1:~# ip netns exec net1 ip link set up eth-0-0
root@invader1:~# 
root@invader1:~# goes vnet show ip fib  
 Table                   Destination           Adjacency
root@invader1:~# ip netns exec net1 ip link set eth-0-0 netns 1
root@invader1:~# 
root@invader1:~# goes vnet show ip fib  
 Table                   Destination           Adjacency
```

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.1.1


1. Assigned secondary IP address to any interface. Moved it into name space:

root@invader42:/# ifconfig xeth5:0 192.168.1.2 netmask 255.255.255.0 up

root@invader42:/# ip add sh xeth5
327: xeth5@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 50:18:4c:00:0e:68 brd ff:ff:ff:ff:ff:ff
    inet 10.0.5.32/24 brd 10.0.5.255 scope global xeth5
       valid_lft forever preferred_lft forever
    inet 192.168.1.2/24 brd 192.168.1.255 scope global xeth5:0
       valid_lft forever preferred_lft forever
    inet6 fe80::5218:4cff:fe00:e68/64 scope link
       valid_lft forever preferred_lft forever
root@invader42:/#

root@invader42:/# goes vnet show ip fib  | grep xeth5
     default                   10.0.5.0/24     7: glean xeth5
     default                  10.0.5.32/32     39: local xeth5
     default                192.168.1.0/24       70: glean xeth5
     default                192.168.1.2/32       69: local xeth5
root@invader42:/#


2. Created a namespace & moved that interface to name space and observed the FIB.

root@invader42:/# ip netns add red
root@invader42:/# ip link set xeth5 netns red
root@invader42:/#
root@invader42:/# ip netns set red 20
root@invader42:/#
root@invader42:/# goes vnet show ip fib  | grep xeth5
root@invader42:/#
root@invader42:/# ip netns exec red ip add sh
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
327: xeth5@if3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 50:18:4c:00:0e:68 brd ff:ff:ff:ff:ff:ff
root@invader42:/#

root@invader42:/# ip netns exec red ip link set up xeth5
root@invader42:/#

3. After bringing up xeth5 in namespace red, made sure that vnet did not add route for the secondary IP address.

root@invader42:/# ip netns exec red ip add sh
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
327: xeth5@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 50:18:4c:00:0e:68 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5218:4cff:fe00:e68/64 scope link
       valid_lft forever preferred_lft forever
root@invader42:/#

root@invader42:/# goes vnet show ip fib  | grep xeth5
root@invader42:/#
root@invader42:/# ip netns exec red ip link set xeth5 netns 1
root@invader42:/# ip link set xeth5 up
root@invader42:/# ifconfig xeth5 10.0.5.32/24

root@invader42:/# ip netns del red
root@invader42:/#
root@invader42:/# goes restart
root@invader42:/#
root@invader42:/home/rohan# goes status
GOES status
------------------------------
  Mode            - XETH
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK

**Result**- Secondary IP is not retained when interface is moved to a namespace.The issue does not reproduce on the latest build(v1.1.1)
