### ISSUE TITLE
"vnet show ip fib summary" crashes with multiple tables

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#56]
- Works with table 0:
```
stig@invader1:~/docker/docker-quagga$ sudo goes vnet show ip fib sum
 Table      Routes
     0          54
Adjacencies: heap 72 used, 2294 free
Fe1 adjacencies: 57 used, 0 free
```
- Move an interface into a docker container.  Now fib has table 0 and table 2:

```
stig@invader1:~/docker/docker-quagga$ sudo goes vnet show ip fib 
 Table                   Destination           Adjacency
     0                  10.15.0.0/24       3: glean eth-0-0
     0                  10.15.0.1/32       4: local eth-0-0
     0                  10.15.0.4/32      55: rewrite eth-0-0 IP4: 02:46:8a:00:02:a3 -> 02:46:8a:00:01:97
     0                  10.32.0.0/24      37: glean eth-12-0
     0                  10.32.0.1/32      38: local eth-12-0
     0                  10.40.0.0/24      15: glean eth-20-0
     0                  10.40.0.1/32      16: local eth-20-0
     2              192.168.200.0/24      56: glean eth-30-0
     2              192.168.200.1/32      57: local eth-30-0
```

- Try summary command again:
 
```
stig@invader1:~/docker/docker-quagga$ sudo goes vnet show ip fib sum
 Table      Routes
     0          54
show ip fib: runtime error: invalid memory address or nil pointer dereference `': goroutine 51 [running]:
runtime/debug.Stack(0xc420190740, 0xbeb883, 0xb)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/platinasystems/go/elib/cli.(*Main).ExecInput.func1(0xc420035e28, 0x131af60, 0xc420190740, 0xc420172270)
	/home/stig/go/src/github.com/platinasystems/go/elib/cli/cli.go:219 +0x9c
panic(0xad8ca0, 0x11fdfb0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/platinasystems/go/vnet/ip4.(*Fib).Len(0x0, 0xc4206041e0)
	/home/stig/go/src/github.com/platinasystems/go/vnet/ip4/fib.go:161 +0xf
github.com/platinasystems/go/vnet/ip4.(*Main).showIpFib(0xc420187b00, 0x131af60, 0xc420190740, 0x7f6f3bb922d0, 0xc4206041e0, 0xc420172270, 0x3, 0xc4206cda68)
	/home/stig/go/src/github.com/platinasystems/go/vnet/ip4/cli.go:58 +0x32e
github.com/platinasystems/go/vnet/ip4.(*Main).(github.com/platinasystems/go/vnet/ip4.showIpFib)-fm(0x131af60, 0xc420190740, 0x7f6f3bb922d0, 0xc4206041e0, 0xc420172270, 0xc420035d00, 0x7f6f3bb922d0)
	/home/stig/go/src/github.com/platinasystems/go/vnet/ip4/cli.go:131 +0x5c
github.com/platinasystems/go/elib/cli.(*Command).CliAction(0xc420190740, 0x7f6f3bb922d0, 0xc4206041e0, 0xc420172270, 0xc4206041e0, 0xc420172270)
	/home/stig/go/src/github.com/platinasystems/go/elib/cli/cli.go:53 +0x59
github.com/platinasystems/go/elib/cli.(*Main).ExecInput(0xc420172270, 0x13161e0, 0xc4206041e0, 0xc420172270, 0x0, 0x0)
	/home/stig/go/src/github.com/platinasystems/go/elib/cli/cli.go:222 +0x134
github.com/platinasystems/go/elib/cli.(*Main).Exec(0xc420172270, 0x13161e0, 0xc4206041e0, 0x1317be0, 0xc420c58f40, 0xf, 0xc15670)
	/home/stig/go/src/github.com/platinasystems/go/elib/cli/cli.go:230 +0x84
github.com/platinasystems/go/elib/cli.(*File).RxReady(0xc4206041e0, 0x42906e, 0xc400000008)
	/home/stig/go/src/github.com/platinasystems/go/elib/cli/file.go:61 +0x222
github.com/platinasystems/go/elib/loop.(*fileEvent).EventAction(0xc420433610)
	/home/stig/go/src/github.com/platinasystems/go/elib/loop/cli.go:38 +0x33
github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc42017e030)
	/home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420172000, 0xc42017e030)
	/home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420172000, 0x131b060, 0xc420172138)
	/home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
	/home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124

```

**Comment by stigt** [comment]
Summary command is happier when not dereferencing nil.

```
stig@invader1:~$ sudo goes vnet show ip fib sum
 Table      Routes
     0          55
     2        4710
     3        4710
Adjacencies: heap 89 used, 2277 free
Fe1 adjacencies: 74 used, 0 free

```

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader44:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader44:/home/rohan# goes version
v1.1.1


1. Checked the FIB summary before moving any interface to container

root@invader42:/# sudo goes vnet show ip fib sum
 Table      Routes
     default           2
Adjacencies: heap 69 used, 0 free
Fe1 next hop usage per pipe: rx [12 11 11 11] tx [5 18 21 1] max 32k
root@invader42:/#

2. Created a container & moved that interface to container and observe FIB summary.

root@invader42:/# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

root@invader42:/# docker run --rm --privileged=true -P --hostname=R1 --name=R1 -d -v $(pwd)/volumes/quagga/R1:/etc/quagga stigt/debian-quagga:latest
`dca1b0817e794169e95c9f2975698c2b8fd4fad15ee80a880e32de5ef92d3d9d`

root@invader42:/# docker ps -a
CONTAINER ID        IMAGE                        COMMAND              CREATED             STATUS              PORTS                                                                                                                        NAMES
dca1b0817e79        stigt/debian-quagga:latest   "/root/startup.sh"   5 seconds ago       Up 3 seconds        0.0.0.0:32772->179/tcp, 0.0.0.0:32771->2601/tcp, 0.0.0.0:32770->2604/tcp, 0.0.0.0:32769->2605/tcp, 0.0.0.0:32768->5201/tcp   R1

root@invader42:/# sudo ./docker_move.sh up R1 xeth5 192.168.120.5/24
root@invader42:/#

root@invader42:/# goes vnet show ip fib
 Table                   Destination                               Adjacency
     default                   10.0.1.0/24     291: glean xeth1
     default                  10.0.1.32/32     292: local xeth1
     default                   10.0.3.0/24     309: glean xeth3
     default                  10.0.3.32/32     310: local xeth3
     default                   10.0.7.0/24     345: glean xeth7
     default                  10.0.7.32/32     346: local xeth7
     default                   10.0.9.0/24     363: glean xeth9
     default                  10.0.9.32/32     364: local xeth9
     default                  10.0.11.0/24     381: glean xeth11
     default                 10.0.11.32/32     382: local xeth11
     default                  10.0.13.0/24     399: glean xeth13
     default                 10.0.13.32/32     400: local xeth13
     default                  10.0.15.0/24     417: glean xeth15
     default                 10.0.15.32/32     418: local xeth15
     default                  10.0.17.0/24     435: glean xeth17
     default                 10.0.17.32/32     436: local xeth17
     default                  10.0.19.0/24     453: glean xeth19
     default                 10.0.19.32/32     454: local xeth19
     default                  10.0.21.0/24     471: glean xeth21
     default                 10.0.21.32/32     472: local xeth21
     default                  10.0.23.0/24     489: glean xeth23
     default                 10.0.23.32/32     490: local xeth23
     default                  10.0.25.0/24     507: glean xeth25
     default                 10.0.25.32/32     508: local xeth25
     default                  10.0.27.0/24     525: glean xeth27
     default                 10.0.27.32/32     526: local xeth27
     default                  10.0.29.0/24     543: glean xeth29
     default                 10.0.29.32/32     544: local xeth29
     default                  10.0.31.0/24     561: glean xeth31
     default                 10.0.31.32/32     562: local xeth31
        4314              192.168.120.0/24       3: glean xeth5
        4314              192.168.120.5/32     327: local xeth5
root@invader42:/#

root@invader42:/# sudo goes vnet show ip fib sum
  Table      Routes
     default           2
          R1           0
Adjacencies: heap 69 used, 0 free
Fe1 next hop usage per pipe: rx [12 11 11 11] tx [5 18 21 1] max 32k
root@invader42:/#


4. Create another container & move interface and check FIB summary.

root@invader42:/# docker run --rm --privileged=true -P --hostname=R2 --name=R2 -d -v $(pwd)/volumes/quagga/R2:/etc/quagga stigt/debian-quagga:latest
93b9350f724013649c616d0bc45cda0c97f1d7b0f89f021a4b0a7c81e2f72921

root@invader42:/# docker ps -a
CONTAINER ID        IMAGE                        COMMAND              CREATED             STATUS              PORTS                                                                                                                        NAMES
93b9350f7240        stigt/debian-quagga:latest   "/root/startup.sh"   7 seconds ago       Up 6 seconds        0.0.0.0:32777->179/tcp, 0.0.0.0:32776->2601/tcp, 0.0.0.0:32775->2604/tcp, 0.0.0.0:32774->2605/tcp, 0.0.0.0:32773->5201/tcp   R2
dca1b0817e79        stigt/debian-quagga:latest   "/root/startup.sh"   2 minutes ago       Up 2 minutes        0.0.0.0:32772->179/tcp, 0.0.0.0:32771->2601/tcp, 0.0.0.0:32770->2604/tcp, 0.0.0.0:32769->2605/tcp, 0.0.0.0:32768->5201/tcp   R1

root@invader42:/# sudo ./docker_move.sh up R2 xeth7 192.168.121.5/24
root@invader42:/#
root@invader42:/#
root@invader42:/# sudo goes vnet show ip fib sum
 Table      Routes
     default         252
        4314           2
        4579           2
Adjacencies: heap 184699 used, 320 free
Fe1 next hop usage: rx [230 229 229 229] tx [129 266 265 257] max 32k
root@invader42:/#

root@invader42:/# ./docker_move.sh down R2 xeth7
root@invader42:/#
root@invader42:/#
root@invader42:/# ./docker_move.sh down R1 xeth5
root@invader42:/#

root@invader42:/# docker stop dca1b0817e79
dca1b0817e79
root@invader42:/#

root@invader42:/#
root@invader42:/# docker stop 93b9350f7240
93b9350f7240
root@invader42:/#
root@invader42:/#
root@invader42:/# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@invader42:/#

**Result**:- Issue not observed ,"vnet show ip summary" did not crash on the latest build (v1.1.1)
