### ISSUE TITLE
using a /31 in a namespace crashes when the link goes down

### ISSUE THREAD

**Issue by stigt** [platinasystems/go#57]

**Comment by stigt** [comment]
Found this crash in docker, but reproduced using just network namespaces:

- Does not happen with /24
```
ip netns add blue
ip link set eth-30-0 netns blue
ip netns set blue 15
ip netns exec blue ip link set up eth-30-0
ip netns exec blue ip add add 10.1.0.2/24 dev eth-30-0

ip netns add red
ip link set eth-31-0 netns red
ip netns set red 16
ip netns exec red ip link set up eth-31-0
ip netns exec red ip add add 10.1.0.3/24 dev eth-31-0
```

- Now ping from red to blue and then bring down the link in blue namespace:

root@invader1:/home/stig# **ip netns exec red ping 10.1.0.2**
PING 10.1.0.2 (10.1.0.2) 56(84) bytes of data.
64 bytes from 10.1.0.2: icmp_seq=1 ttl=64 time=0.173 ms
64 bytes from 10.1.0.2: icmp_seq=2 ttl=64 time=0.097 ms
^C
--- 10.1.0.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1010ms
rtt min/avg/max/mdev = 0.097/0.135/0.173/0.038 ms

root@invader1:/home/stig# **ip netns exec blue ip link set down eth-30-0**

root@invader1:/home/stig# **goes status**
```
GOES status
======================
  PCI             - OK
  Kernel module   - OK
  Check daemons:
    goes-daemons  - OK
    redisd        - OK
    qsfp          - OK
    vnetd         - OK
    uptimed       - OK
    i2cd          - OK
  Check Redis     - OK
  Check vnet      - OK
```

- Now try with /31 instead:

```
ip netns add blue
ip link set eth-30-0 netns blue
ip netns set blue 15
ip netns exec blue ip link set up eth-30-0
ip netns exec blue ip add add 10.1.0.2 peer 10.1.0.3/31 dev eth-30-0

ip netns add red
ip link set eth-31-0 netns red
ip netns set red 16
ip netns exec red ip link set up eth-31-0
ip netns exec red ip add add 10.1.0.3 peer 10.1.0.2/31 dev eth-31-0
```

- Ping from red to blue and take down blue interface

root@invader1:/home/stig# **ip netns exec red ping 10.1.0.2**
PING 10.1.0.2 (10.1.0.2) 56(84) bytes of data.
64 bytes from 10.1.0.2: icmp_seq=1 ttl=64 time=0.263 ms
64 bytes from 10.1.0.2: icmp_seq=2 ttl=64 time=0.095 ms
^C
--- 10.1.0.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1006ms
rtt min/avg/max/mdev = 0.095/0.179/0.263/0.084 ms

root@invader1:/home/stig# **ip netns exec blue ip link set down eth-30-0**

root@invader1:/home/stig# **goes status**
```
GOES status
======================
  PCI             - OK
  Kernel module   - OK
  Check daemons:
    goes-daemons  - OK
    redisd        - OK
    i2cd          - OK
    uptimed       - OK
    qsfp          - OK
    **vnetd         - not running**
```

- Stack trace:
```
get route: goroutine 50 [running]:
runtime/debug.Stack(0xc420a69aa0, 0xa85500, 0xc420faa4d0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc4201a0000)
        /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x72
panic(0xa85500, 0xc420faa4d0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/platinasystems/go/vnet/ethernet.(*ipNeighborMain).AddDelIpNeighbor(0xc4201dc068, 0xc4200df668, 0xc4210c6280, 0x7c03000101, 0x1, 0x0)
        /home/stig/go/src/github.com/platinasystems/go/vnet/ethernet/neighbor.go:82 +0x90b
github.com/platinasystems/go/vnet/unix.(*Main).ip4NeighborMsg(0xc4201e0500, 0xc4200ec540, 0x0, 0x0)
        /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:489 +0x32c
github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc4209d4090)
        /home/stig/go/src/github.com/platinasystems/go/vnet/unix/netlink.go:360 +0x609
github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc420a02060)
        /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc4201a0000, 0xc420a02060)
        /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc4201a0000, 0x13225c0, 0xc4201a0548)
        /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
        /home/stig/go/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
done

```

**Comment by stigt** [comment]
Fixed by this commit by Eliot -https://github.com/platinasystems/go/commit/1d38bcbd21ac3c9bf8160364968c1f23f5e7fdec

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.1.1

1. Executed the following commands on invader-45 which will create a namespace named as blue and will move xeth13 interface to the namespace

root@invader45:/home/rohan# ip netns add blue
root@invader45:/home/rohan# ip link set xeth13 netns blue
root@invader45:/home/rohan# ip netns set blue 15
root@invader45:/home/rohan# ip netns exec blue ip link set up xeth13
root@invader45:/home/rohan# ip netns exec blue ip add add 10.1.0.2 peer 10.1.0.3/31 dev xeth13
root@invader45:/home/rohan# ip netns exec blue ip link set down xeth13


2. Executed the following commdans on invader-43 which will create a namespace named as red and will move xeth13 interface to the namespace

root@invader43:/home/rohan# ip netns add red
root@invader43:/home/rohan# ip link set xeth13 netns red
root@invader43:/home/rohan# ip netns set red 16
root@invader43:/home/rohan# ip netns exec red ip link set up xeth13
root@invader43:/home/rohan# ip netns exec red ip add add 10.1.0.3 peer 10.1.0.2/31 dev xeth13

3. Initiated ping from red namespace to blue namespace and validated that ping replies can be seen

root@invader43:/home/sandeep#  ip netns exec red ping 10.1.0.2
PING 10.1.0.2 (10.1.0.2) 56(84) bytes of data.
64 bytes from 10.1.0.2: icmp_seq=1 ttl=64 time=0.565 ms
64 bytes from 10.1.0.2: icmp_seq=2 ttl=64 time=0.181 ms
64 bytes from 10.1.0.2: icmp_seq=3 ttl=64 time=0.246 ms


4. Brought down xeth13 interface from blue namespace while continuous ping requests were coming from red namespace

root@invader45:/home/sandeep# ip netns exec blue ip link set down xeth13

5. Validated on red namespace under invader-43 that ping replies are not coming anymore
root@invader43:/home/rohan# ip netns exec red ping 10.1.0.2
PING 10.1.0.2 (10.1.0.2) 56(84) bytes of data.
^C
--- 10.1.0.2 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2039ms


6. On invader-45 verify if vnetd deamon is up and running after bringing down xeth13 interface which is mapped to blue namespace

root@invader45:/home/sandeep# goes status
GOES status
-------------------------------
  Mode            - XETH
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK


7. Bring up xeth13 interface from blue namespace while continues ping requests are coming from red namespace & validate that ping replies can be seen

root@invader45:/home/sandeep# ip netns exec blue ip link set up xeth13

8. Repeat step-4 to step-7 for 3 times & validate that vnetd service is up & running on invader-45

9. After execution of the above test steps remove the namespaces created under invader-45 & invader-43 & restart goes service

root@invader45:/home/sandeep# ip netns del blue
root@invader43:/home/sandeep# ip netns del red

root@invader45:/home/sandeep# goes restart

root@invader43:/home/sandeep# goes restart

root@invader45:/home/sandeep# goes status
GOES status
------------------------------
  Mode            - XETH
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK

root@invader43:/home/sandeep# goes status
GOES status
-------------------------------
  Mode            - XETH
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK

**Result**:- No name-space crash observed . This works fine on the latest build(v1.1.1)
