### ISSUE TITLE
Panic after 'sh ip fib'

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#6]
Build version:
```
commit 71edbc1d0d43cdeb99cd618db30d0cb33d8ef355
Author: Tom Grennan <tgrennan@platinasystems.com>
Date:   Fri Dec 30 17:34:31 2016 -0800
```

(pulled and built on 1/3/2017)

After running a local script that adds (and subsequently deletes) 1536 static routes w/ "ip route add ..." / "ip route del ...", after ~15mins my script detected FIB inconsistency (rib=0, fib=1 route). Returning after lunch and seeing this, I did:

```
donn@invader8:~$ sudo goes vnet sh ip fib
[sudo] password for donn:
 Table                   Destination           Adjacency
     0              192.168.155.0/24  1: glean eth-31-0
     0              192.168.155.2/32  3: rewrite eth-31-0 IP4: 02:46:8a:00:05:b4 -> 00:05:64:2f:3c:c9
     0              192.168.155.3/32  2: local eth-31-0
                                        tx pipe packets                2
                                        tx pipe bytes                196
donn@invader8:~$
```

And vnet must have died, because a few secs later I did 'sh ip fib' again and saw this:

```
donn@invader8:~$ sudo goes vnet sh ip fib | egrep " 20\.[0-9]+" | wc -l
vnet: dial unix /run/goes/socks/vnet: connect: connection refused
0
donn@invader8:~$
```

Then saw this in syslog:

```
Jan  5 12:26:34 invader8 goes.vnetd[31085]: panic: write broken pipe
Jan  5 12:26:34 invader8 goes.vnetd[31085]:
Jan  5 12:26:34 invader8 goes.vnetd[31085]: goroutine 12 [running]:
Jan  5 12:26:34 invader8 goes.vnetd[31085]: panic(0xa18aa0, 0xc4225fc0a0)
Jan  5 12:26:34 invader8 goes.vnetd[31085]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Jan  5 12:26:34 invader8 goes.vnetd[31085]: github.com/platinasystems/go/elib/iomux.(*Mux).do(0x12253a0, 0xc420045350)
Jan  5 12:26:34 invader8 goes.vnetd[31085]:         /home/donn/workspace/go/src/github.com/platinasystems/go/elib/iomux/epoll.go:143 +0x186
Jan  5 12:26:34 invader8 goes.vnetd[31085]: github.com/platinasystems/go/elib/iomux.(*Mux).EventPoll(0x12253a0)
Jan  5 12:26:34 invader8 goes.vnetd[31085]:         /home/donn/workspace/go/src/github.com/platinasystems/go/elib/iomux/epoll.go:166 +0xde
Jan  5 12:26:34 invader8 goes.vnetd[31085]: github.com/platinasystems/go/elib/loop.(*eventLoop).eventPoller(0xc4200cee68, 0x12054e0, 0x12253a0)
Jan  5 12:26:34 invader8 goes.vnetd[31085]:         /home/donn/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:156 +0x31
Jan  5 12:26:34 invader8 goes.vnetd[31085]: created by github.com/platinasystems/go/elib/loop.(*eventLoop).startPoller
Jan  5 12:26:34 invader8 goes.vnetd[31085]:         /home/donn/workspace/go/src/github.com/platinasystems/go/elib/loop/event.go:159 +0x53
Jan  5 12:26:36 invader8 goes.vnetd[31085]: exit status 2
```

which agrees with the date/time of my 1st 'sh ip fib'.

Complete syslog is stored in invader8:~donn/syslog_panic_2017_01_05.txt

Steps to reproduce:
Use a script to add 1536 /31 routes to kernel RIB.
Have script delete those routes.
Pause 5 seconds.
Compare RIB and FIB.
If FIB is in sync with RIB, repeat test.

Another observation:  I suspect that vnet was lagging and not keeping sync with kernel's route table because my script pauses 5 seconds before comparing the kernel RIB to vnet FIB.
After 5 secs, the number of RIB routes was 0 (correct), but the FIB route count was 1 (incorrect, should be zero after all 1536 routes were deleted).
When I issued 'sh ip fib' manually (an hr later and before vnet died), it showed 0 of the test routes (20.x.x.x/31 routes), which is correct.  But then vnet died.

**Comment by donnlee** [comment]
Note, this seems to be the exact same panic I reported via email to bugs@ on 12/15/2016.

**Comment by donnlee** [comment]
Sometimes I run my test script and vnet doesn't die, but it is out-of-sync with the kernel rib.
I often have to wait 10s of seconds, even over 60s, for the fib to equal the rib.
Often it is the *last* added route that is missing from the fib.
That is: Often 1535 of the 1536 routes are in the fib immediately, but the 1536th route can take 60s or more to appear in the fib.
This applies to both adds and deletes of routes.  That is, if I remove 1536 routes from the rib, 1535 routes will be removed from the fib immediately, but the 1536th route that was deleted will take >30s to disappear from the fib.

Run script and allow fib 35s (delay const in script) to catch-up to rib before comparing "fib=rib?":

```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ while ./route_add_and_del.py; do date; sleep 2; done; while : ; do sudo goes vnet sh ip fib; date; sleep 5; done
```

Wait about 5mins and fib inconsistency is detected by the script:

```
<cut script output lines>
Done with adds.
Sleeping 35s...
Linux routes: 1536
Wrong number of vnet routes, 1535. Expected 1536. Quitting!
```

Note time when we ctrl-c out of script:

```
Thu Jan  5 15:55:43 PST 2017
^C
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$
```

See there are 1535 routes (should be 1536):

donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo goes vnet sh ip fib | egrep " 20\.[0-9]+" | wc -l; date
1535
Thu Jan  5 15:55:50 PST 2017

Keep checking:

```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo goes vnet sh ip fib | egrep " 20\.[0-9]+" | wc -l; date
1535
Thu Jan  5 15:56:21 PST 2017
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo goes vnet sh ip fib | egrep " 20\.[0-9]+" | wc -l; date
1535
Thu Jan  5 15:56:25 PST 2017
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo goes vnet sh ip fib | egrep " 20\.[0-9]+" | wc -l; date
1535
Thu Jan  5 15:56:30 PST 2017
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo goes vnet sh ip fib | egrep " 20\.[0-9]+" | wc -l; date
1535
Thu Jan  5 15:56:35 PST 2017
```

Finally, at 15:56:40 we see all 1536 routes in fib:

```
donn@invader8:~/workspace/gitlab.com/donnlee/tor/invader/testing/fib_testing$ sudo goes vnet sh ip fib | egrep " 20\.[0-9]+" | wc -l; date
1536
Thu Jan  5 15:56:40 PST 2017
```

Why does it take so long for the last route to be added (or deleted)?

**Comment by donnlee** [comment]
On latest code, I have not seen a failure after 24h of isolated testing.
I would like to repeat this test with all of the following in-play on the tor:
1. This fib test.
2. Medium scp file transfer over punt path (one link to neighbor).
3. Normal collectd/grafana monitoring.

**Comment by donnlee** [comment]
Tested OK. Closing this issue.
goes version:
```
commit 54a7307587b68120234ff7da4a6471c1379a02b9
Author: Mark Pleso <mpleso@platinasystems.com>
Date:   Tue Jan 24 12:06:13 2017 -0800

    Added RPCs to I2C Server Daemon
```
...BUT with anti-thread-locking patch applied by dlobete to my tree on i8:
```
-rwxr-xr-x  1 donn donn 22641035 Jan 30 10:22 goes-platina-mk1.0130.SPECIAL_don_anti.thread.lock
```

Running on i22 (beta hw).

Ran the following for 24hrs:

- Punt path traffic between i22 and i14 (100Mbps scp file transfer loop).
- Redis subscriber (subscribe2.go) publishing collectd stats to influxdb/grafana.
- My static route churn script running and checking rib/fib consistency.

No issues.

**Comment by RohanK-Calsoft** [comment]
Tested this isuue on the new build:-

`root@invader44:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader44:/home/rohan# goes version
v1.1.1`

1) Ran a local script to create 1536 static routes:-
`root@invader29:/home/rohan# cat routeaddnew.sh

for ((i=1; i<=6; i++))
        do

                for ((j=1; j<=255; j++))

                        do
                        var="1.1.${i}.${j}"
                        route add -net $var netmask 255.255.255.255 gw 10.0.5.32
                        done

        done
root@invader29:/home/rohan# ./routeaddnew.sh`

2) Checked both the routing table and the 'goes vnet show ip fib'

`root@invader44:/home/rohan# ip ro
default via 172.17.2.1 dev eth0
1.1.1.1 via 10.0.5.32 dev xeth5
1.1.1.2 via 10.0.5.32 dev xeth5
.
.
1.1.6.255 via 10.0.5.32 dev xeth5

3)root@invader44:/home/rohan# goes vnet show ip fib
 default              1.1.1.1/32      ---------      via            10.0.5.32 dev      xeth5 weight   1  unreachable

.
.
  default             1.1.6.255/32      ---------      via            10.0.5.32 dev      xeth5 weight   1  unreachable
`
3) Restarted the 'goes' and checked the entries again in both tables and all the entries were visible in both routing and the goes table. Checked the goes status as well:-

root@invader44:/home/rohan# goes status
GOES status
----------------------------------
  Mode            - XETH
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK

Result :- Did not observe any panic. Works fine on the latest build, version:- v1.1.1.
