### ISSUE TITLE
Large (1000B) ping between invaders fails

### ISSUE THREAD

**Issue by donnlee** [platinasystems/go#61]
Happens on v0.2 and latest eng build.

1. Cold boot
1. Wait for goes to start
1. Ping neighbor invader with 1000B packets
1. See 50-70% packet loss

if 500B pings, loss is noticeably lower.
if 200B pings, no loss (but I did a short 1m test).

```
donn@invader8:~$ gobgp nei
Peer             AS  Up/Down State       |#Advertised Received Accepted
10.9.31.16    65216 21:21:42 Establ      |         40       57       57
10.10.31.17   65217 21:21:41 Establ      |         31       57       57
192.168.155.2 65202 00:00:33 Establ      |         62        0        0
donn@invader8:~$ ip ro get 10.9.31.16
10.9.31.16 dev eth-30-0  src 10.9.31.8
    cache

donn@invader8:~$ ping -i .3 -s 1000 10.9.31.16
PING 10.9.31.16 (10.9.31.16) 1000(1028) bytes of data.
1008 bytes from 10.9.31.16: icmp_seq=2 ttl=64 time=0.241 ms
1008 bytes from 10.9.31.16: icmp_seq=3 ttl=64 time=0.181 ms
1008 bytes from 10.9.31.16: icmp_seq=5 ttl=64 time=0.233 ms
1008 bytes from 10.9.31.16: icmp_seq=6 ttl=64 time=0.126 ms
1008 bytes from 10.9.31.16: icmp_seq=7 ttl=64 time=0.212 ms
<...>
^C
--- 10.9.31.16 ping statistics ---
229 packets transmitted, 135 received, 41% packet loss, time 71972ms
rtt min/avg/max/mdev = 0.085/0.164/0.758/0.069 ms
donn@invader8:~$
```

@dlobete was able to repro easily using his i5 and i4.
He has found some interesting TH counters showing up (underrun pkts), digging, and isolating the issue.

I see the counter incrementing on my setup:

```
donn@invader16:~$ goes vnet show ha | grep under
donn@invader16:~$ goes vnet show ha | grep under
                                                           port tx fifo underrun packets                    4
donn@invader16:~$ goes vnet show ha | grep under
                                                           port tx fifo underrun packets                    6
donn@invader16:~$ goes vnet show ha | grep under
                                                           port tx fifo underrun packets                    7
donn@invader16:~$ goes vnet show ha | grep under
                                                           port tx fifo underrun packets                    9
donn@invader16:~$ goes vnet show ha | grep under
                                                           port tx fifo underrun packets                   10
donn@invader16:~$ goes vnet show ha | grep under
                                                           port tx fifo underrun packets                   11
```

**Comment by dlobete** [comment]
Transit (i.e. routed) ICMP packets of this size are ok. This issue affects packets punted from fe1a to ixgbe.

**Comment by dlobete** [comment]
Bad port mode setting for meth caused problems with large packets for meth-1.
Resolved with:
commit a404698d6c02a67447afc6957424b9762225a674
Author: Don Lobete <dlobete@platinasystems.com>
Date:   Wed Aug 2 12:51:00 2017 -0700

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.1.1

1. Verified that xeth1 link is up on both invader-29 & invader-31

root@invader29:/home/sandeep# goes hget platina-mk1 link |grep xeth1
vnet.xeth1.link: true
root@invader31:/home/sandeep# goes hget platina-mk1 link |grep xeth1
vnet.xeth1.link: true

2. Rebooted invader-31

3. As soon as invader-31 was UP ,executeed the following cmd to ping invader-29’s xeth1 interface
root@invader31:/home/sandeep# ping -s 2000 10.0.1.29 -c 5
PING 10.0.1.29 (10.0.1.29) 2000(2028) bytes of data.
2008 bytes from 10.0.1.29: icmp_seq=1 ttl=64 time=0.190 ms
2008 bytes from 10.0.1.29: icmp_seq=2 ttl=64 time=0.225 ms
2008 bytes from 10.0.1.29: icmp_seq=3 ttl=64 time=0.212 ms
2008 bytes from 10.0.1.29: icmp_seq=4 ttl=64 time=0.188 ms
2008 bytes from 10.0.1.29: icmp_seq=5 ttl=64 time=0.117 ms

--- 10.0.1.29 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4079ms
rtt min/avg/max/mdev = 0.117/0.186/0.225/0.039 ms

     4. Verified that there are no packet loss after ping operation completes

**Result**: Issue is not reproduced on the new build. No ping loss observed.
