### ISSUE TITLE
redis not up during goes start

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#7]
Occasionally, redis.ready does not get asserted on goes start.  goes start fails with when checking vnet.ready = true; but failure is due to redis not up (redis.ready never asserted)

 

When fail:

In, redisd.go,

func Main(args …string):

…

err = Hook(pub) returns err “read: no such device or address”

…

**Comment by tgrennan** [comment]
Please attach /var/log/daemon.log and output of `ps -e f`

**Comment by fszyang** [comment]
"ps -e f" dump.  (Note goes never completed the install because of vnet.ready check timeout)

root@invader2:/home/platina# ps -e f
  PID TTY      STAT   TIME COMMAND
    2 ?        S      0:00 [kthreadd]
    3 ?        S      0:00  \_ [ksoftirqd/0]
    5 ?        S<     0:00  \_ [kworker/0:0H]
    7 ?        S      0:00  \_ [rcu_sched]
    8 ?        S      0:00  \_ [rcu_bh]
    9 ?        S      0:00  \_ [migration/0]
   10 ?        S      0:00  \_ [cpuhp/0]
   11 ?        S      0:00  \_ [cpuhp/1]
   12 ?        S      0:00  \_ [migration/1]
   13 ?        S      0:00  \_ [ksoftirqd/1]
   15 ?        S<     0:00  \_ [kworker/1:0H]
   16 ?        S      0:00  \_ [cpuhp/2]
   17 ?        S      0:00  \_ [migration/2]
   18 ?        S      0:00  \_ [ksoftirqd/2]
   20 ?        S<     0:00  \_ [kworker/2:0H]
   21 ?        S      0:00  \_ [cpuhp/3]
   22 ?        S      0:00  \_ [migration/3]
   23 ?        S      0:00  \_ [ksoftirqd/3]
   25 ?        S<     0:00  \_ [kworker/3:0H]
   26 ?        S      0:00  \_ [cpuhp/4]
   27 ?        S      0:00  \_ [migration/4]
   28 ?        S      0:00  \_ [ksoftirqd/4]
   30 ?        S<     0:00  \_ [kworker/4:0H]
   31 ?        S      0:00  \_ [cpuhp/5]
   32 ?        S      0:00  \_ [migration/5]
   33 ?        S      0:00  \_ [ksoftirqd/5]
   35 ?        S<     0:00  \_ [kworker/5:0H]
   36 ?        S      0:00  \_ [cpuhp/6]
   37 ?        S      0:00  \_ [migration/6]
   38 ?        S      0:00  \_ [ksoftirqd/6]
   40 ?        S<     0:00  \_ [kworker/6:0H]
   41 ?        S      0:00  \_ [cpuhp/7]
   42 ?        S      0:00  \_ [migration/7]
   43 ?        S      0:00  \_ [ksoftirqd/7]
   45 ?        S<     0:00  \_ [kworker/7:0H]
   46 ?        S      0:00  \_ [kdevtmpfs]
   47 ?        S<     0:00  \_ [netns]
   48 ?        S      0:00  \_ [oom_reaper]
   49 ?        S<     0:00  \_ [writeback]
   50 ?        S      0:00  \_ [kcompactd0]
   51 ?        S<     0:00  \_ [crypto]
   52 ?        S<     0:00  \_ [bioset]
   53 ?        S<     0:00  \_ [kblockd]
   54 ?        S<     0:00  \_ [ata_sff]
   55 ?        S<     0:00  \_ [md]
   78 ?        S      0:00  \_ [kswapd0]
   79 ?        S<     0:00  \_ [vmstat]
   91 ?        S<     0:00  \_ [acpi_thermal_pm]
   93 ?        S      0:00  \_ [scsi_eh_0]
   94 ?        S<     0:00  \_ [scsi_tmf_0]
   95 ?        S      0:00  \_ [scsi_eh_1]
   96 ?        S<     0:00  \_ [scsi_tmf_1]
   97 ?        S      0:00  \_ [scsi_eh_2]
   98 ?        S<     0:00  \_ [scsi_tmf_2]
   99 ?        S      0:00  \_ [scsi_eh_3]
  100 ?        S<     0:00  \_ [scsi_tmf_3]
  101 ?        S      0:00  \_ [scsi_eh_4]
  102 ?        S<     0:00  \_ [scsi_tmf_4]
  103 ?        S      0:00  \_ [scsi_eh_5]
  104 ?        S<     0:00  \_ [scsi_tmf_5]
  108 ?        S      0:00  \_ [kworker/u16:5]
  110 ?        S      0:00  \_ [kworker/5:1]
  114 ?        S<     0:00  \_ [vfio-irqfd-clea]
  116 ?        S<     0:00  \_ [ipv6_addrconf]
  132 ?        S<     0:00  \_ [deferwq]
  133 ?        S<     0:00  \_ [bioset]
  179 ?        S<     0:00  \_ [kworker/4:1H]
  196 ?        S<     0:00  \_ [kworker/1:1H]
  198 ?        S      0:00  \_ [jbd2/sda2-8]
  199 ?        S<     0:00  \_ [ext4-rsv-conver]
  286 ?        S<     0:00  \_ [kvm-irqfd-clean]
  613 ?        S<     0:00  \_ [kworker/2:1H]
  642 ?        S<     0:00  \_ [kworker/6:1H]
  722 ?        S<     0:00  \_ [kworker/5:1H]
  740 ?        S<     0:00  \_ [kworker/3:1H]
  796 ?        S<     0:00  \_ [kworker/0:1H]
 1694 ?        S<     0:00  \_ [kworker/7:1H]
 2282 ?        S      0:00  \_ [kworker/7:0]
 3202 ?        S      0:00  \_ [kworker/1:0]
 3245 ?        S      0:00  \_ [kworker/2:0]
 3581 ?        S      0:00  \_ [kworker/3:0]
 3679 ?        S      0:00  \_ [kworker/4:2]
 3763 ?        S      0:00  \_ [kworker/6:0]
 4526 ?        S      0:00  \_ [kworker/0:2]
 9442 ?        S      0:00  \_ [kworker/u16:0]
10437 ?        S      0:00  \_ [kworker/7:2]
10969 ?        S      0:00  \_ [kworker/5:2]
20375 ?        S      0:00  \_ [kworker/2:1]
20462 ?        S      0:00  \_ [kworker/3:2]
20619 ?        S      0:00  \_ [kworker/6:2]
20705 ?        S      0:00  \_ [kworker/4:0]
22769 ?        S      0:00  \_ [kworker/0:1]
23991 ?        S      0:00  \_ [kworker/1:1]
 5314 ?        S      0:00  \_ [kworker/u16:1]
    1 ?        Ss     0:11 /sbin/init
  251 ?        Ss     0:01 /lib/systemd/systemd-journald
  255 ?        Ss     0:01 /lib/systemd/systemd-udevd
  323 ?        Ssl    0:00 /lib/systemd/systemd-timesyncd
  360 ?        Ss     0:05 /usr/sbin/sshd -D
 2314 ?        Ss     0:00  \_ sshd: platina [priv]
 2325 ?        S      0:00      \_ sshd: platina@pts/0
 2327 pts/0    Ss     0:00          \_ -bash
 8591 pts/0    S+     0:00              \_ tmux new
  361 ?        Ss     0:00 /usr/sbin/cron -f
  363 ?        Ss     0:00 /lib/systemd/systemd-logind
  366 ?        Ss     0:01 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
  374 ?        Ss     0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 104:109
  379 ?        Ssl    0:00 /usr/sbin/rsyslogd -n
  410 ?        Ss     0:00 /usr/sbin/acpid
  602 ?        Sl     0:01 python -O lisp-core.pyo 8080
  606 tty1     Ss+    0:00 /sbin/agetty --noclear tty1 linux
  646 ?        Sl     0:03 python -O lisp-etr.pyo
  671 ?        Sl     0:14 python -O lisp-itr.pyo
  842 ttyS0    Ss+    0:00 /sbin/agetty --keep-baud 115200 38400 9600 ttyS0 vt102
 2319 ?        Ss     0:01 /lib/systemd/systemd --user
 2322 ?        S      0:00  \_ (sd-pam)
 8593 ?        Ss     0:00 tmux new
 8594 pts/1    Ss     0:00  \_ -bash
 8609 pts/1    S      0:00      \_ sudo -s
 8615 pts/1    S      0:00          \_ /bin/bash
 5346 pts/1    R+     0:00              \_ ps -e f

**Comment by fszyang** [comment]
daemon.log dump.  Most of those are prints I've added to code for debug.

Jan  6 13:49:47 invader2 goes.redisd[4877]: goes.Main []
Jan  6 13:49:47 invader2 goes.redisd[4877]: new arg =  [redisd]
Jan  6 13:49:47 invader2 goes.redisd[4877]: next command g := byName[redisd]
Jan  6 13:49:47 invader2 goes.redisd[4877]: g.Kind.IsDaemon() = true
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main Hello==========================
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main finished varrun stuffs==========================
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main finished starting server===/run/goes/socks/redisd
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main finished chgroup adm===/run/goes/socks/redisd
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main finished assign, unassign===/run/goes/socks/redisd
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main published hostname = invader2
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main published machine = platina-mk1
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main published cmdline.console = ttyS0,115200
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main published cmdline.loglevel = 3
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main published cmdline.root = /dev/sda2
Jan  6 13:49:47 invader2 goes.redisd[4877]: listen: /run/goes/socks/redisd
Jan  6 13:49:47 invader2 goes.redisd[4877]: listen: [127.0.0.1%lo]:6379
Jan  6 13:49:47 invader2 goes.redisd[4877]: listen: [12.12.12.12%lo]:6379
Jan  6 13:49:47 invader2 goes.redisd[4877]: listen: [2001:5:3::12%lo]:6379
Jan  6 13:49:47 invader2 goes.redisd[4877]: listen: [::1%lo]:6379
Jan  6 13:49:47 invader2 goes.redisd[4877]: listen: [172.30.0.101%eth0]:6379
Jan  6 13:49:47 invader2 goes.redisd[4877]: listen: [fe80::46:8aff:fe00:3ac%eth0]:6379
Jan  6 13:49:47 invader2 goes.redisd[4877]: redisd.main Hook(pub) and pubish ready; err = read: no such device or address
Jan  6 13:49:47 invader2 goes.redisd[4877]: read: no such device or address
Jan  6 13:49:47 invader2 goes.redisd[4877]: done
Jan  6 13:49:57 invader2 goes.goes-daemons[4871]: (platina,redis.ready) timeout

**Comment by fszyang** [comment]
Issue closed.  Fixed by 23dc8f245807a35d0f796e4040513ab177ac711c

Issue was caused by I2C access conflict between BMC and x86 during EEPROM read as redisd is coming up.  
Removed the contention from BMC side.

Verified with 1500+ goes stop/start loop and all passed
