### ISSUE TITLE
eth-0-0 doesn't come back into linux after moving out of namespace

### ISSUE THREAD

**Issue by jasonlpang** [platinasystems/go#70]
If I move a port into a namespace and then back out, it doesn't appear in linux anymore.  The other 31 ports do not exhibit this behavior.  I see this on both invader29 and invader21.  I modified the device version field to try both 1-based and 0-based port numbering but both show the issue.

master branch, top of tree as of yesterday
go: 1bdf6f582730375401e27ec7568cc8b23338e0a2
fe1: 98433cbb12382a04230132c34d19227ba224cbbf
firmware: 60f39141fbbf78ddb2260dba74c68f2789374f18
system-build: d0bc8489f5cf0fffd15d787ca5ffa70cacc60ede

//eth-0-0 doesn't come back:
root@invader29:\~# ip netns add net1
root@invader29:\~# ip link set eth-0-0 netns net1
root@invader29:\~# sudo ip netns exec net1 ip add show
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
7: eth-0-0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 50:18:4c:00:05:a0 brd ff:ff:ff:ff:ff:ff
root@invader29:\~# ip netns exec net1 ip link set eth-0-0 netns 1
root@invader29:\~# ip link show eth-0-0
Device "eth-0-0" does not exist.
root@invader29:\~# ip link set eth-0-0 netns net1
Cannot find device "eth-0-0"

//eth-1-0 works ok:
root@invader29:\~# ip link set eth-1-0 netns net1
root@invader29:\~# sudo ip netns exec net1 ip add show
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
8: eth-1-0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 50:18:4c:00:05:a1 brd ff:ff:ff:ff:ff:ff
root@invader29:\~# ip link show eth-0-0^C
root@invader29:\~# ip netns exec net1 ip link set eth-1-0 netns 1
root@invader29:\~# ip link show eth-1-0
8: eth-1-0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:05:a1 brd ff:ff:ff:ff:ff:ff

**Comment by dlobete** [comment]
FWIW, it seems ok on inv5:
root@invader5:/home/dlobete/src/github.com/platinasystems/go# ip link set eth-0-0 netns ns5
root@invader5:/home/dlobete/src/github.com/platinasystems/go# ip netns exec ns5 ip link set dev eth-0-0 netns 1
root@invader5:/home/dlobete/src/github.com/platinasystems/go# ifconfig eth-0-0
eth-0-0   Link encap:Ethernet  HWaddr 02:46:8a:00:04:35  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:796 (796.0 B)

**Comment by jasonlpang** [comment]
It’s also ok on invader1, it’s likely something about how I’m setting up the invaders.  However Invader29 is a new system that just went through ansible dev setup so I’m not sure what I’m doing differently.

**Comment by jasonlpang** [comment]
/etc/udev/rules.d/70-persistent-net.rules was assigning the port to eth3 in the default namespace.  Once the rule was removed the interface came back normally when returned to the default namespace.  thanks Don and Stig!
