### ISSUE TITLE
ifconfig state out of sync with goes and ip route

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#78]
version: dcb42afc1f93cfd8a6d1d4cdb8c6549f37d3761f

## Everything in sync after goes start

platina@invader29:$ goes hget platina eth-1-1.admin
vnet.eth-1-1.admin: true
platina@invader29:$ goes hget platina eth-1-1.link
vnet.eth-1-1.link: true
platina@invader29:$ sudo ifconfig eth-1-1
eth-1-1   Link encap:Ethernet  HWaddr 50:18:4c:00:05:a0  
          inet addr:10.0.1.29  Bcast:10.0.1.255  Mask:255.255.255.0
          inet6 addr: fe80::5218:4cff:fe00:5a0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:786 (786.0 B)

platina@invader29:$ ip link show eth-1-1
583: eth-1-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:05:a0 brd ff:ff:ff:ff:ff:ff

## First ifdown works OK

platina@invader29:$ sudo ifdown eth-1-1
platina@invader29:$ sudo ifconfig eth-1-1
eth-1-1   Link encap:Ethernet  HWaddr 50:18:4c:00:05:a0  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:786 (786.0 B)

platina@invader29:$ ip link show eth-1-1
583: eth-1-1: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:05:a0 brd ff:ff:ff:ff:ff:ff
platina@invader29:$ goes hget platina eth-1-1.admin
vnet.eth-1-1.admin: false
platina@invader29:$ goes hget platina eth-1-1.link
vnet.eth-1-1.link: false

## First ifup after work OK

platina@invader29:$ sudo ifup eth-1-1
platina@invader29:$ sudo ifconfig eth-1-1
eth-1-1   Link encap:Ethernet  HWaddr 50:18:4c:00:05:a0  
          inet addr:10.0.1.29  Bcast:10.0.1.255  Mask:255.255.255.0
          inet6 addr: fe80::5218:4cff:fe00:5a0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:1572 (1.5 KiB)

platina@invader29:$ ip link show eth-1-1
583: eth-1-1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:05:a0 brd ff:ff:ff:ff:ff:ff
platina@invader29:$ goes hget platina eth-1-1.admin
vnet.eth-1-1.admin: true
platina@invader29:$ goes hget platina eth-1-1.link
vnet.eth-1-1.link: true

## The next ifdown, and any subsequest ifup/down, has no effect on goes/redis

platina@invader29:$ sudo ifdown eth-1-1
platina@invader29:$ sudo ifconfig eth-1-1
eth-1-1   Link encap:Ethernet  HWaddr 50:18:4c:00:05:a0  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:1572 (1.5 KiB)

platina@invader29:$ ip link show eth-1-1
583: eth-1-1: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:05:a0 brd ff:ff:ff:ff:ff:ff
platina@invader29:$ goes hget platina eth-1-1.admin
vnet.eth-1-1.admin: true  (should be false)
platina@invader29:$ goes hget platina eth-1-1.link
vnet.eth-1-1.link: true (should be false)

## Repeatable 100% of the time in this sequence
Recoverable only after goes restart

**Comment by stigt** [comment]
On a related note, I'm having an email exchange with Don & Eliot regarding link state alway being true on the linux side even when there is no carrier.  In my example I'm leaving admin up, but changing auto-neg settings to cause link to go down.

```
root@invader1:/home/stig# goes hget platina vnet.eth-3-0.link
true
root@invader1:/home/stig# goes hset platina vnet.eth-3-0.speed 100G
1
root@invader1:/home/stig# goes hget platina vnet.eth-3-0.link
false

root@invader1:/home/stig# ip ad sh eth-3-0
107: eth-3-0: <BROADCAST,UP,LOWER_UP> mtu 4352 qdisc pfifo_fast state UP group default qlen 5000
    link/ether 02:46:8a:00:02:a6 brd ff:ff:ff:ff:ff:ff
    inet 10.6.0.1/24 brd 10.6.0.255 scope global eth-3-0
       valid_lft forever preferred_lft forever
    inet6 fe80::46:8aff:fe00:2a6/64 scope link 
       valid_lft forever preferred_lft forever
```
This cause problems for apps link keepalived which needs to fail-over when carrier goes away.

**Comment by fszyang** [comment]
At some point in my test of port up/down, vnet went into unrecoverable state where it continues writes to syslog with message not about to addDelReplace adjacency on an address of eth-1-1.
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/24
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/32

Go status would hang waiting for vnet to respond

```
platina@invader29:~$ sudo goes status
GOES status
======================
  PCI             - OK
  Kernel module   - OK
  Check daemons:
    goes-daemons  - OK
    redisd        - OK
    qsfp          - OK
    vnetd         - OK
    i2cd          - OK
    uptimed       - OK
  Check Redis     - OK
  Check vnet      - 

```
Aug 28 14:49:47 invader29 kernel: ixgbevf 0000:03:17.4: NIC Link is Up 10 Gbps
Aug 28 14:49:47 invader29 kernel: IPv6: ADDRCONF(NETDEV_UP): eth-31-1: link is not ready
Aug 28 14:49:47 invader29 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth-31-1: link becomes ready
Aug 28 14:49:47 invader29 systemd[1]: Reloading OpenBSD Secure Shell server.
Aug 28 14:49:47 invader29 systemd[1]: Reloaded OpenBSD Secure Shell server.
Aug 28 14:49:53 invader29 kernel: ixgbe 0000:03:00.0 eth1: VF Reset msg received from vf 0
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/24
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/32
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/24
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/32
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/24
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/32
Aug 28 14:49:53 invader29 goes.vnetd[15057]: addDelReplace adjacency not found 10.0.1.29/24
(went on for 3 hours...)

**Comment by fszyang** [comment]
Fixed and Closed.  Also for best practice, use iproute2 instead of ifconfig commands
Tested on:
fyang@invader2:~$ sudo goes hget platina packages | grep version:
    version: 12bd0121f22fb1d63ccc9879cc7fe11464655f7c
    version: 1af481b2eff2a5368950b58aac47b5e313ea7663
    version: 60f39141fbbf78ddb2260dba74c68f2789374f18

**Comment by RohanK-Calsoft** [comment]
Verified this issue on the latest build:-

root@invader42:/home/rohan# goes vnetd -version
fe1: v1.1.3
fe1a: v1.1.0
vnet-platina-mk1: v1.0.0

root@invader42:/home/rohan# goes version
v1.1.1


1. Restarted goes.

2. Executed the below commands to check the "ifconfig" state synced with goes or not. Toggled the interface up and down, to check the sync.

root@invader42:/home/rohan# goes hget platina-mk1 xeth9.admin
vnet.xeth9.admin: true

root@invader42:/home/rohan# goes hget platina-mk1 xeth9.link
vnet.xeth9.link: true

root@invader42:/home/rohan# ifconfig xeth9
xeth9     Link encap:Ethernet  HWaddr 50:18:4c:00:0e:6c
          inet addr:10.0.9.32  Bcast:10.0.9.255  Mask:255.255.255.0
          inet6 addr: fe80::5218:4cff:fe00:e6c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:83 errors:0 dropped:45 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:17521 (17.1 KiB)  TX bytes:268 (268.0 B)

root@invader42:/home/rohan# ip link show xeth9
365: xeth9@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:0e:6c brd ff:ff:ff:ff:ff:ff

root@invader42:/home/rohan# ifdown xeth9

root@invader42:/home/rohan# ifconfig xeth9
xeth9     Link encap:Ethernet  HWaddr 50:18:4c:00:0e:6c
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:86 errors:0 dropped:47 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:18160 (17.7 KiB)  TX bytes:268 (268.0 B)

root@invader42:/home/rohan# ip link show xeth9
365: xeth9@eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:0e:6c brd ff:ff:ff:ff:ff:ff
root@invader42:/home/rohan# goes hget platina-mk1 xeth9.admin
vnet.xeth9.admin: false
root@invader42:/home/rohan# goes hget platina-mk1 xeth9.link
vnet.xeth9.link: false

root@invader42:/home/rohan# ifup xeth9
root@invader42:/home/rohan#
root@invader42:/home/rohan# ifconfig xeth9
xeth9     Link encap:Ethernet  HWaddr 50:18:4c:00:0e:6c
          inet addr:10.0.9.32  Bcast:10.0.9.255  Mask:255.255.255.0
          inet6 addr: fe80::5218:4cff:fe00:e6c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:89 errors:0 dropped:48 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:18641 (18.2 KiB)  TX bytes:1082 (1.0 KiB)
root@invader42:/home/rohan#
root@invader42:/home/rohan# ip link show xeth9
365: xeth9@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:0e:6c brd ff:ff:ff:ff:ff:ff# goes hget platina-mk1 xeth9.admin
vnet.xeth9.admin: true
root@invader42:/home/rohan#
root@invader42:/home/rohan# goes hget platina-mk1 xeth9.link
vnet.xeth9.link: true

root@invader42:/home/rohan# ifdown xet
root@invader42:/home/rohan# ifconfig xeth9
xeth9   Link encap:Ethernet  HWaddr 50:18:4c:00:0e:84
          BROADCAST  MTU:9216  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:19 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:5000
          RX bytes:1535 (1.4 KiB)  TX bytes:2547 (2.4 KiB)

root@invader42:/home/rohan# goes hget platina-mk1 xeth9.admin
vnet.xeth9.admin: false
root@invader42:/home/rohan# goes hget platina-mk1 xeth9.link
vnet.xeth9.link: false

root@invader42:/home/rohan# ip link show xeth9
365: xeth9@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:0e:6c brd ff:ff:ff:ff:ff:ff

root@invader42:/home/rohan# ifup xeth9

root@invader42:/home/rohan# ifconfig xeth9
xeth9   Link encap:Ethernet  HWaddr 50:18:4c:00:0e:84
          inet addr:10.0.9.32  Bcast:10.0.9.255  Mask:255.255.255.0
          inet6 addr: fe80::5218:4cff:fe00:e84/64 Scope:Link
          UP BROADCAST RUNNING  MTU:9216  Metric:1
          RX packets:12 errors:0 dropped:0 overruns:0 frame:0
          TX packets:27 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:5000
          RX bytes:1998 (1.9 KiB)  TX bytes:3536 (3.4 KiB)

root@invader42:/home/rohan# ip link show xeth9
365: xeth9@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 50:18:4c:00:0e:6c brd ff:ff:ff:ff:ff:ff

root@invader42:/home/rohan# goes hget platina-mk1 xeth9.admin
vnet.xeth9.admin: true

root@invader42:/home/rohan# goes hget platina-mk1 xeth9.link
vnet.xeth9.link: true

Result:- Issue does not reproduce on the latest build(v1.1.1).
