### ISSUE TITLE
vnet panic with "brctl addif br0 eth0"

### ISSUE THREAD

**Issue by jasonlpang** [platinasystems/go#84]
I was trying out linux bridging and ran into this vnet panic when I added eth0 to a bridge interface. 

$ brctl addbr br0
$ goes status
GOES status
  Mode            - TUNTAP
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - OK
$ brctl addif br0 eth0
$ sudo goes status
GOES status
  Mode            - TUNTAP
  PCI             - OK
  Check daemons   - OK
  Check Redis     - OK
  Check vnet      - 
Not OK
status: vnetd daemon not responding

Aug 20 16:08:43 invader21 goes.vnetd[8338]: panic: vnet: runtime error: invalid memory address or nil pointer dereference
Aug 20 16:08:43 invader21 goes.vnetd[8338]: goroutine 31 [running]:
Aug 20 16:08:43 invader21 goes.vnetd[8338]: runtime/debug.Stack(0xbb3d20, 0xc421a621e0, 0xc42308bad8)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Aug 20 16:08:43 invader21 goes.vnetd[8338]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler.func1(0xc42020c000, 0xc42020c558)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:181 +0x159
Aug 20 16:08:43 invader21 goes.vnetd[8338]: panic(0xbcfc20, 0x1465c00)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /usr/local/go/src/runtime/panic.go:489 +0x2cf
Aug 20 16:08:43 invader21 goes.vnetd[8338]: github.com/platinasystems/go/internal/netlink.(*IfInfoMessage).InterfaceKind(0xc42015b200, 0x9debcb)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /home/jpang/gopath/src/github.com/platinasystems/go/internal/netlink/attr.go:300 +0x5c
Aug 20 16:08:43 invader21 goes.vnetd[8338]: github.com/platinasystems/go/vnet/unix.(*net_namespace).forDummyInterface(0xc420262090, 0xc42015b200, 0x0)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:124 +0x2f
Aug 20 16:08:43 invader21 goes.vnetd[8338]: github.com/platinasystems/go/vnet/unix.(*net_namespace).msg_for_vnet_interface(0xc420262090, 0x15ce880, 0xc42015b200, 0x0)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:191 +0x3c1
Aug 20 16:08:43 invader21 goes.vnetd[8338]: github.com/platinasystems/go/vnet/unix.(*netlinkEvent).EventAction(0xc4225ccf40)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /home/jpang/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:455 +0xfb
Aug 20 16:08:43 invader21 goes.vnetd[8338]: github.com/platinasystems/go/elib/loop.(*nodeEvent).do(0xc421874140)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:152 +0x8f
Aug 20 16:08:43 invader21 goes.vnetd[8338]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc42020c000, 0x15bfdc0, 0xc42020c550)
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:195 +0x175
Aug 20 16:08:43 invader21 goes.vnetd[8338]: created by github.com/platinasystems/go/elib/loop.(*Node).maybeStartEventHandler
Aug 20 16:08:43 invader21 goes.vnetd[8338]:         /home/jpang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:280 +0x29f

$ goes hget platina packages | grep version:
    version: 6333fc5ddb8af6bab471b786ec12f3224e0ce253
    version: 02162ebd396bd87633477cd34c10775cdc199e8f
    version: 60f39141fbbf78ddb2260dba74c68f2789374f18

**Comment by stigt** [comment]
Fixed with:

```
Branch: refs/heads/master
  Home:   https://github.com/platinasystems/go
  Commit: 9deb570a474423bda52f2bcbbb6d13a350ec1426
      https://github.com/platinasystems/go/commit/9deb570a474423bda52f2bcbbb6d13a350ec1426
  Author: Stig Thormodsrud <stig@platinasystems.com>
  Date:   2017-12-12 (Tue, 12 Dec 2017)

  Changed paths:
    M internal/netlink/attr.go

  Log Message:
  -----------
  check for nil before dereferencing
```
