### ISSUE TITLE
goes vnet show ip fib command's output is not displaying loop back interface entry

### ISSUE THREAD

**Issue by jignesh045** [platinasystems/go#89]
Issue Description: goes vnet show ip fib command's output is not displaying loop back interface entry

Note: This issue is discovered while executing following test case: Regress_GeneralRouting_Quagga_BGP_ Consistency_0125 which is related to quagga BGP Consistency check between Quagga, goes & linux.

Environment: Testbed setup1 (invader29, Invader30, Invader31, Invader32)

root@invader29:/home/jignesh# goes hget platina packages | grep version:

    version: 412434633cb86f71ef19e9df3ee85de33dab1f84
    version: 581c0a529a332cdab0e8f767130c48fd3b8b0f01
    version: 60f39141fbbf78ddb2260dba74c68f2789374f18

root@invader29:/home/jignesh#

Steps:

Follow the steps mentioned in test case: Regress_GeneralRouting_Quagga_BGP_ Consistency_0125 under Regress Test document copied to google drive with doc name: Platina detail Regression test case.

Verify the following three command output (output is also available in doc):

1. root@invader29:/# vtysh -c "sh ip route"
2. root@invader29:/# route
3. root@invader29:/# goes vnet show ip fib

Compare the output for all available network entries with each others output. In this case, Invader29 has Loop back & docker0 interface configured but it's entries are missing in goes vnet show ip fib command's output.

**Comment by mj073** [comment]
As per my understanding so far 'goes vnet show ip fib' would show the forwarding information of the "TUN" type interfaces only. 
Following will show the types of interfaces:
```
root@invader29:~# goes vnet show netlink namespaces
           Interface           Type            Namespace           NSID
br-5966ece8cb56               bridge            default
br-a459773cbb9a               bridge            default
docker0                       bridge            default
dummy0                         dummy            default
eth-1-1                         tun             default
eth-2-1                         tun             default
eth-3-1                         tun             default
eth-4-1                         tun             default
eth-5-1                         tun             default
eth-6-1                         tun             default
eth-7-1                         tun             default
eth-8-1                         tun             default
eth-9-1                         tun             default
eth-10-1                        tun             default
eth-11-1                        tun             default
eth-12-1                        tun             default
eth-13-1                        tun             default
eth-14-1                        tun             default
eth-15-1                        tun             default
eth-16-1                        tun             default
eth-17-1                        tun             default
eth-18-1                        tun             default
eth-19-1                        tun             default
eth-20-1                        tun             default
eth-21-1                        tun             default
eth-22-1                        tun             default
eth-23-1                        tun             default
eth-24-1                        tun             default
eth-25-1                        tun             default
eth-26-1                        tun             default
eth-27-1                        tun             default
eth-28-1                        tun             default
eth-29-1                        tun             default
eth-30-1                        tun             default
eth-31-1                        tun             default
eth-32-1                        tun             default
eth0                                            default
lo                                              default
vnet                            tun             default
root@invader29:~#
```
For this test case we should have compared the output with "goes ip route" cmd instead of "goes vnet show ip fib".

Please correct me if I am wrong...

**Comment by fszyang** [comment]
"goes vnet show ip fib" is an engineering command that shows the FIB on the interfaces that belong to the ASIC.  eth0 and loopback interface are not part of ASIC interface.
