### ISSUE TITLE
Unable to establish communication between loopback interfaces in Quagga

### ISSUE THREAD

**Issue by sans2864** [platinasystems/go#90]
Issue Description:Observed that loopback interface ip's could not communicate with each other even though the OSPF routes are established between them

Environment: Testbed setup1(invader-29 & invader-31)

Goes version:
github.com/platinasystems/go: v0.4-687-gb5c22f8'
github.com/platinasystems/fe1: v0.3-236-g581c0a5
github.com/platinasystems/firmware-fe1a: v0.2

Steps to reproduce

- Used OSPF protocol to configure routes between invader-29 & invader-31 through eth-7-1 interface
- On invader-29 updated the ip address of loopback interface to 192.168.29.1/24
		root@invader29:/home/sandeep# ifconfig lo 192.168.29.1 netmask 255.255.255.0 up
		root@invader29:/home/sandeep# ifconfig lo
lo        Link encap:Local Loopback
          inet addr:192.168.29.1  Mask:255.255.255.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3285491 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3285491 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2866767066 (2.6 GiB)  TX bytes:2866767066 (2.6 GiB)

		  
- On invader-31 updated the ip address of loopback interface to 192.168.31.1/24
		root@invader31:/home/sandeep# ifconfig lo 192.168.31.1/24 up
		root@invader31:/home/sandeep# ifconfig lo
lo        Link encap:Local Loopback
          inet addr:192.168.31.1  Mask:255.255.255.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:24596145 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24596145 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:22010734044 (20.4 GiB)  TX bytes:22010734044 (20.4 GiB)

 
- configured OSPF routes on invader-29 through vtysh shell

root@invader29:/home/sandeep# vtysh

!
interface vnet
!
router ospf
 ospf router-id 172.17.2.29
 network 10.0.7.0/24 area 0.0.0.0
 network 192.168.29.0/24 area 0.0.0.0
!
line vty

- Configured OSPF routes in invader-31 through vtysh shell
root@invader31:/home/sandeep# vtysh
!
router ospf
 ospf router-id 172.17.2.31
 network 10.0.7.0/24 area 0.0.0.0
 network 192.168.31.0/24 area 0.0.0.0
!

Observations

- Observed that the OSPF routes for neighbor loopback network can be seen on the respective invader's

On invader-29

invader29# show ip ospf route
============ OSPF network routing table ============
N    10.0.7.0/24           [10] area: 0.0.0.0
                           directly attached to eth-7-1
N    192.168.29.1/32       [10] area: 0.0.0.0
                           directly attached to lo
N    192.168.31.1/32       [20] area: 0.0.0.0
                           via 10.0.7.31, eth-7-1

============ OSPF router routing table =============

============ OSPF external routing table ===========

On invader-31

============ OSPF network routing table ============
N    10.0.7.0/24           [10] area: 0.0.0.0
                           directly attached to eth-7-1
N    192.168.29.1/32       [20] area: 0.0.0.0
                           via 10.0.7.29, eth-7-1
N    192.168.31.1/32       [10] area: 0.0.0.0
                           directly attached to lo

- Intiatited ping request from invader-29 to invader-31 loopback interface but could not see any replies

root@invader29:/home/sandeep# ping -I lo 192.168.31.1
PING 192.168.31.1 (192.168.31.1) from 192.168.29.1 lo: 56(84) bytes of data.
--- 192.168.31.1 ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 6139ms

- Intiatited ping request from invader-31 to invader-29 loopback interface but could not see any replies
root@invader31:/home/sandeep# ping -I lo 192.168.29.1
PING 192.168.29.1 (192.168.29.1) from 192.168.31.1 lo: 56(84) bytes of data.
--- 192.168.29.1 ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7165ms

**Comment by fszyang** [comment]
The correct configuration is to use dummy interface instead of loopback interface:
Closed
